In [160]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import os

In [161]:
proj_dir = os.path.join(Path.home(), 'Documents', 'WorkSpace', 'corpus-comparison')
analysis_dir = os.path.join(proj_dir, 'analysis')
corpora_dir = os.path.join(proj_dir, 'corpora')

print(f"Project directory: {proj_dir}")
print(f"Analysis directory: {analysis_dir}")
print(f"Corpora directory: {corpora_dir}")

Project directory: /Users/bagjuhyeon/Documents/WorkSpace/corpus-comparison
Analysis directory: /Users/bagjuhyeon/Documents/WorkSpace/corpus-comparison/analysis
Corpora directory: /Users/bagjuhyeon/Documents/WorkSpace/corpus-comparison/corpora

# File-processing

기존 처리된 파일에서 LDT Obs가 빠져서 이것만 merging 이후 필요한 것만 뽑아서 다시 정리.

## convert csv -> xlsx

In [162]:
ELP_LDT_data_path = os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT.csv')

if os.path.exists(ELP_LDT_data_path):
    df = pd.read_csv(ELP_LDT_data_path)
    df.to_excel(os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT.xlsx'), index=False)
    print("Conversion complete: word_stimuli.csv -> word_stimuli.xlsx")
else:
    raise FileNotFoundError(f"File not found: {ELP_LDT_data_path}")

Conversion complete: word_stimuli.csv -> word_stimuli.xlsx

In [163]:
ELP_LDT_data = pd.read_excel(os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT.xlsx'))
ELP_LDT_data

,Word,Length,Freq_HAL,Log_Freq_HAL,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,"10,610,626",16.177,"20,415.270",798.917,-0.013,333.849,24,0.73
1,aah,3,222,5.403,52.710,816.429,0.214,186.029,21,0.62
2,Aaron,5,"10,806",9.288,14.650,736.062,-0.111,289.010,32,0.97
3,aback,5,387,5.958,0.290,796.267,0.110,171.607,15,0.45
4,abacus,6,513,6.240,0.240,964.400,0.655,488.996,15,0.47
...,...,...,...,...,...,...,...,...,...,...
40476,zoom,4,"4,920",8.501,3.550,549.758,-0.762,97.649,33,1.00
40477,zooming,7,523,6.260,0.630,709.690,-0.293,283.106,29,0.88
40478,zooms,5,385,5.953,0.060,666.933,-0.476,232.109,30,0.94
40479,zucchini,8,314,5.749,0.960,848.679,0.239,259.819,28,0.85
40480,Zurich,6,"1,770",7.479,2.430,763.000,0.091,184.257,21,0.64

lower

In [164]:
ELP_LDT_data['Word'] = ELP_LDT_data['Word'].str.lower()
ELP_LDT_data

,Word,Length,Freq_HAL,Log_Freq_HAL,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,"10,610,626",16.177,"20,415.270",798.917,-0.013,333.849,24,0.73
1,aah,3,222,5.403,52.710,816.429,0.214,186.029,21,0.62
2,aaron,5,"10,806",9.288,14.650,736.062,-0.111,289.010,32,0.97
3,aback,5,387,5.958,0.290,796.267,0.110,171.607,15,0.45
4,abacus,6,513,6.240,0.240,964.400,0.655,488.996,15,0.47
...,...,...,...,...,...,...,...,...,...,...
40476,zoom,4,"4,920",8.501,3.550,549.758,-0.762,97.649,33,1.00
40477,zooming,7,523,6.260,0.630,709.690,-0.293,283.106,29,0.88
40478,zooms,5,385,5.953,0.060,666.933,-0.476,232.109,30,0.94
40479,zucchini,8,314,5.749,0.960,848.679,0.239,259.819,28,0.85
40480,zurich,6,"1,770",7.479,2.430,763.000,0.091,184.257,21,0.64

In [167]:
remove_cols = ELP_LDT_data.columns.to_list()
remove_cols.remove('Obs')
remove_cols.remove('Word')
remove_cols

['Length',
 'Freq_HAL',
 'Log_Freq_HAL',
 'SUBTLWF',
 'I_Mean_RT',
 'I_Zscore',
 'I_SD',
 'I_Mean_Accuracy']

left only obs info

In [168]:
ELP_LDT_data.drop(columns=remove_cols, inplace=True)
ELP_LDT_data

           Word Obs
0             a  24
1           aah  21
2         aaron  32
3         aback  15
4        abacus  15
...         ...  ..
40476      zoom  33
40477   zooming  29
40478     zooms  30
40479  zucchini  28
40480    zurich  21

[40481 rows x 2 columns]

기존 merged 된 file read.

In [169]:
KE_ELP_path = os.path.join(corpora_dir, 'merged_corpora', 'CSAT_E_final.xlsx')
KE_ELP = pd.read_excel(KE_ELP_path)
KE_ELP

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Freq_HAL,SUBTLWF,Freq_KF,CSAT_RFreq,CSAT_only_RFreq,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,POS
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,24675.191037,23843.796660,...,NaN,NaN,NaN,798.917,-0.013,333.849,662.087,-0.323,174.691,minor|NN
1,aah,3,NaN,NaN,NaN,222,2688.21,1.0,NaN,NaN,...,NaN,NaN,NaN,816.429,0.214,186.029,646.400,-0.349,130.445,NaN
2,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,9.867257,2.439762,...,NaN,NaN,NaN,736.062,-0.111,289.010,686.111,-0.203,179.290,NN
3,aback,5,NaN,NaN,NaN,387,14.79,2.0,NaN,NaN,...,NaN,NaN,NaN,796.267,0.110,171.607,596.538,-0.550,89.453,RB
4,abacus,6,NaN,NaN,NaN,513,12.24,NaN,NaN,NaN,...,NaN,NaN,NaN,964.400,0.655,488.996,792.688,0.309,200.186,NN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zooming,7,NaN,NaN,NaN,523,32.13,1.0,NaN,NaN,...,NaN,NaN,NaN,709.690,-0.293,283.106,672.370,-0.218,92.353,VB
40477,zooms,5,NaN,NaN,NaN,385,3.06,1.0,NaN,NaN,...,NaN,NaN,NaN,666.933,-0.476,232.109,613.833,-0.552,88.295,VB
40478,zucchini,8,NaN,NaN,NaN,314,48.96,NaN,NaN,NaN,...,6.3,4.18,6.19,848.679,0.239,259.819,756.000,0.207,209.064,NN
40479,zurich,6,NaN,NaN,NaN,1770,123.93,2.0,NaN,NaN,...,NaN,NaN,NaN,763.000,0.091,184.257,822.640,0.213,221.482,NN
40480,NaN,4,NaN,NaN,NaN,15410,27.03,13.0,NaN,NaN,...,NaN,NaN,NaN,703.467,-0.278,168.922,595.741,-0.562,86.852,NN|JJ

merged obs data

In [ ]:
KE_ELP = pd.merge(KE_ELP, ELP_LDT_data, on='Word', how='inner')
KE_ELP.reset_index(drop=True)
KE_ELP.columns

Index(['Word', 'Length', 'CSAT_Freq', 'CSAT_only_Freq', 'Textbook_only_Freq',
       'Freq_HAL', 'SUBTLWF', 'Freq_KF', 'CSAT_RFreq', 'CSAT_only_RFreq',
       'Textbook_only_RFreq', 'RFreq_HAL', 'SUBTLRWF', 'RFreq_KF',
       'Ortho_N_CSAT', 'Ortho_N_CSAT(only)', 'Ortho_N_Textbook(only)',
       'Ortho_N', 'OLD20_CSAT', 'OLD20_CSAT(only)', 'OLD20_Textbook(only)',
       'OLD', 'SUBTLCD', 'Concreteness_Rating', 'Age_Of_Acquisition',
       'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance',
       'I_Mean_RT', 'I_Zscore', 'I_SD', 'I_NMG_Mean_RT', 'I_NMG_Zscore',
       'I_NMG_SD', 'POS', 'Obs'],
      dtype='object')

In [172]:
renamed_cols = {
    'CSAT_Freq': 'KE_Freq',
    'CSAT_only_Freq': 'KE(EXAM)_Freq',
    'Textbook_only_Freq': 'KE(TEXTBOOK)_Freq',
    'SUBTLWF': 'SUBTLEX_Freq',
    'Freq_KF': 'KF_Freq',
    'CSAT_RFreq': 'KE_RFreq',
    'CSAT_only_RFreq': 'KE(EXAM)_RFreq',
    'Textbook_only_RFreq': 'KE(TEXTBOOK)_RFreq',
    'RFreq_HAL': 'HAL_RFreq',
    'SUBTLRWF': 'SUBTLEX_RFreq',
    'RFreq_KF': 'KF_RFreq',
    'Ortho_N_CSAT': 'KE_Ortho_N',
    'Ortho_N_CSAT(only)': 'KE(EXAM)_Ortho_N',
    'Ortho_N_Textbook(only)': 'KE(TEXTBOOK)_Ortho_N',
    'OLD20_CSAT': 'KE_OLD',
    'OLD20_CSAT(only)': 'KE(EXAM)_OLD',
    'OLD20_Textbook(only)': 'KE(TEXTBOOK)_OLD',
    'I_Mean_RT' : 'LDT_Mean_RT', 
    'I_Zscore' : 'LDT_RT_Zscore',
    'I_SD' : 'LDT_RT_SD', 
    'I_NMG_Mean_RT' : 'NMG_Mean_RT', 
    'I_NMG_Zscore' : 'NMG_RT_Zscore',
    'I_NMG_SD' : 'NMG_RT_SD',
    'Obs': 'LDT_Obs'
}

KE_ELP.rename(columns=renamed_cols, inplace=True)

In [ ]:
KE_ELP.columns

Index(['Word', 'Length', 'KE_Freq', 'KE(EXAM)_Freq', 'KE(TEXTBOOK)_Freq',
       'Freq_HAL', 'SUBTLEX_Freq', 'KF_Freq', 'KE_RFreq', 'KE(EXAM)_RFreq',
       'KE(TEXTBOOK)_RFreq', 'HAL_RFreq', 'SUBTLEX_RFreq', 'KF_RFreq',
       'KE_Ortho_N', 'KE(EXAM)_Ortho_N', 'KE(TEXTBOOK)_Ortho_N', 'Ortho_N',
       'KE_OLD', 'KE(EXAM)_OLD', 'KE(TEXTBOOK)_OLD', 'OLD', 'SUBTLCD',
       'Concreteness_Rating', 'Age_Of_Acquisition', 'Emotional_Valence',
       'Emotional_Arousal', 'Emotional_Dominance', 'LDT_Mean_RT',
       'LDT_RT_Zscore', 'LDT_RT_SD', 'NMG_Mean_RT', 'NMG_RT_Zscore',
       'NMG_RT_SD', 'POS', 'LDT_Obs'],
      dtype='object')

In [177]:
column_order = ['Word', 'Length', 
                'KE_Freq', 'KE(EXAM)_Freq', 'KE(TEXTBOOK)_Freq', 'Freq_HAL', 'SUBTLEX_Freq', 'KF_Freq', 
                'KE_RFreq', 'KE(EXAM)_RFreq', 'KE(TEXTBOOK)_RFreq', 'HAL_RFreq', 'SUBTLEX_RFreq', 'KF_RFreq',
                'KE_Ortho_N', 'KE(EXAM)_Ortho_N', 'KE(TEXTBOOK)_Ortho_N', 'Ortho_N',
                'KE_OLD', 'KE(EXAM)_OLD', 'KE(TEXTBOOK)_OLD', 'OLD', 
                'SUBTLCD',
                'Concreteness_Rating', 'Age_Of_Acquisition', 'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance', 
                'LDT_Mean_RT', 'LDT_RT_Zscore', 'LDT_RT_SD', 'LDT_Obs',
                'NMG_Mean_RT', 'NMG_RT_Zscore', 'NMG_RT_SD', 
                'POS']

In [179]:
KE_ELP = KE_ELP[column_order]
KE_ELP.reset_index(drop=True, inplace=True)

In [180]:
KE_ELP.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_E_final(250921).xlsx'), index=False)

In [181]:
KE_ELP

,Word,Length,KE_Freq,KE(EXAM)_Freq,KE(TEXTBOOK)_Freq,Freq_HAL,SUBTLEX_Freq,KF_Freq,KE_RFreq,KE(EXAM)_RFreq,...,Emotional_Arousal,Emotional_Dominance,LDT_Mean_RT,LDT_RT_Zscore,LDT_RT_SD,LDT_Obs,NMG_Mean_RT,NMG_RT_Zscore,NMG_RT_SD,POS
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,24675.191037,23843.796660,...,NaN,NaN,798.917,-0.013,333.849,24,662.087,-0.323,174.691,minor|NN
1,aah,3,NaN,NaN,NaN,222,2688.21,1.0,NaN,NaN,...,NaN,NaN,816.429,0.214,186.029,21,646.400,-0.349,130.445,NaN
2,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,9.867257,2.439762,...,NaN,NaN,736.062,-0.111,289.010,32,686.111,-0.203,179.290,NN
3,aback,5,NaN,NaN,NaN,387,14.79,2.0,NaN,NaN,...,NaN,NaN,796.267,0.110,171.607,15,596.538,-0.550,89.453,RB
4,abacus,6,NaN,NaN,NaN,513,12.24,NaN,NaN,NaN,...,NaN,NaN,964.400,0.655,488.996,15,792.688,0.309,200.186,NN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zooming,7,NaN,NaN,NaN,523,32.13,1.0,NaN,NaN,...,NaN,NaN,709.690,-0.293,283.106,29,672.370,-0.218,92.353,VB
40477,zooms,5,NaN,NaN,NaN,385,3.06,1.0,NaN,NaN,...,NaN,NaN,666.933,-0.476,232.109,30,613.833,-0.552,88.295,VB
40478,zucchini,8,NaN,NaN,NaN,314,48.96,NaN,NaN,NaN,...,4.18,6.19,848.679,0.239,259.819,28,756.000,0.207,209.064,NN
40479,zurich,6,NaN,NaN,NaN,1770,123.93,2.0,NaN,NaN,...,NaN,NaN,763.000,0.091,184.257,21,822.640,0.213,221.482,NN
40480,NaN,4,NaN,NaN,NaN,15410,27.03,13.0,NaN,NaN,...,NaN,NaN,703.467,-0.278,168.922,30,595.741,-0.562,86.852,NN|JJ

In [191]:
KE_ELP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Word                  40480 non-null  object
 1   Length                40481 non-null  int64
 2   KE_Freq               16354 non-null  float64
 3   KE(EXAM)_Freq         14009 non-null  float64
 4   KE(TEXTBOOK)_Freq     11801 non-null  float64
 5   Freq_HAL              40481 non-null  int64
 6   SUBTLEX_Freq          35515 non-null  float64
 7   KF_Freq               32552 non-null  float64
 8   KE_RFreq              16354 non-null  float64
 9   KE(EXAM)_RFreq        14009 non-null  float64
 10  KE(TEXTBOOK)_RFreq    11801 non-null  float64
 11  HAL_RFreq             40481 non-null  float64
 12  SUBTLEX_RFreq         35515 non-null  float64
 13  KF_RFreq              32552 non-null  float64
 14  KE_Ortho_N            16354 non-null  float64
 15  KE(EXAM)_Ortho_N      14009 non-null  float64
 16  KE(TEXTBOOK)_Ortho_N  11801 non-null  float64
 17  Ortho_N               40481 non-null  int64
 18  KE_OLD                16354 non-null  float64
 19  KE(EXAM)_OLD          14009 non-null  float64
 20  KE(TEXTBOOK)_OLD      11801 non-null  float64
 21  OLD                   39382 non-null  float64
 22  SUBTLCD               35515 non-null  float64
 23  Concreteness_Rating   23562 non-null  float64
 24  Age_Of_Acquisition    31440 non-null  float64
 25  Emotional_Valence     12742 non-null  float64
 26  Emotional_Arousal     12742 non-null  float64
 27  Emotional_Dominance   12742 non-null  float64
 28  LDT_Mean_RT           40468 non-null  float64
 29  LDT_RT_Zscore         40468 non-null  float64
 30  LDT_RT_SD             40450 non-null  float64
 31  LDT_Obs               40481 non-null  object
 32  NMG_Mean_RT           40481 non-null  float64
 33  NMG_RT_Zscore         40481 non-null  float64
 34  NMG_RT_SD             40477 non-null  float64
 35  POS                   39903 non-null  object
dtypes: float64(30), int64(3), object(3)
memory usage: 11.1+ MB

In [194]:
KE_ELP[['KE_RFreq', 'HAL_RFreq', 'SUBTLEX_RFreq', 'KF_RFreq']].corr()

               KE_RFreq  HAL_RFreq  SUBTLEX_RFreq  KF_RFreq
KE_RFreq       1.000000   0.989188       0.817785  0.954049
HAL_RFreq      0.989188   1.000000       0.799306  0.954787
SUBTLEX_RFreq  0.817785   0.799306       1.000000  0.656533
KF_RFreq       0.954049   0.954787       0.656533  1.000000

In [195]:
KE_ELP[['KE_RFreq', 'HAL_RFreq', 'SUBTLEX_RFreq', 'KF_RFreq']].corr(method='spearman')

               KE_RFreq  HAL_RFreq  SUBTLEX_RFreq  KF_RFreq
KE_RFreq       1.000000   0.729815       0.678321  0.688789
HAL_RFreq      0.729815   1.000000       0.801952  0.736892
SUBTLEX_RFreq  0.678321   0.801952       1.000000  0.668395
KF_RFreq       0.688789   0.736892       0.668395  1.000000

In [198]:
KE_ELP['KE_Freq'] = KE_ELP['KE_Freq'].fillna(0)
KE_ELP['KE_Freq'].describe()

count    40481.000000
mean        17.524691
std        316.267203
min          0.000000
25%          0.000000
50%          0.000000
75%          3.000000
max      38303.000000
Name: KE_Freq, dtype: float64

In [ ]:
# 아 어지럽네,, HAL은 freq 범위가 0이 있네 ㅋㅋㅋ 이러면 correlation이 조금 달라지지.
# 찾아보니 corpus 간 비교는 일반적으로 출현하지 않은 단어는 0으로 처리하고 correlation 하라네?
KE_ELP['Freq_HAL'].sort_values(ascending=False)

36085    23099033
36561    12661276
24276    11003606
1285     10715411
0        10610626
           ...
13673           0
38072           0
13489           0
13310           0
17515           0
Name: Freq_HAL, Length: 40481, dtype: int64

In [192]:
KE_ELP[KE_ELP['Freq_HAL'] == 0]

,Word,Length,KE_Freq,KE(EXAM)_Freq,KE(TEXTBOOK)_Freq,Freq_HAL,SUBTLEX_Freq,KF_Freq,KE_RFreq,KE(EXAM)_RFreq,...,Emotional_Arousal,Emotional_Dominance,LDT_Mean_RT,LDT_RT_Zscore,LDT_RT_SD,LDT_Obs,NMG_Mean_RT,NMG_RT_Zscore,NMG_RT_SD,POS
135,abstractors,11,NaN,NaN,NaN,0,NaN,1.0,NaN,NaN,...,NaN,NaN,942.857,0.473,389.840,28,744.444,0.034,180.613,NN
630,affectingly,11,NaN,NaN,NaN,0,NaN,1.0,NaN,NaN,...,NaN,NaN,927.654,0.620,334.334,26,831.652,0.332,241.508,RB
742,aggrieve,8,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,NaN,837.455,0.171,302.046,22,763.682,0.085,271.183,VB
755,agleam,6,NaN,NaN,NaN,0,NaN,1.0,NaN,NaN,...,NaN,NaN,1375.000,0.672,685.894,2,891.333,0.431,383.182,JJ
811,airbed,6,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,NaN,717.633,-0.215,217.586,30,643.815,-0.302,109.351,NN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39996,wireworm,8,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,NaN,957.609,0.469,370.709,23,810.120,0.272,284.113,NN
40107,woodgraining,12,NaN,NaN,NaN,0,NaN,1.0,NaN,NaN,...,NaN,NaN,1055.913,0.831,347.469,23,841.429,0.470,259.581,VB
40129,woolworkers,11,NaN,NaN,NaN,0,NaN,1.0,NaN,NaN,...,NaN,NaN,876.742,0.231,266.742,31,767.423,0.112,167.535,NN
40145,workbag,7,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,NaN,871.379,0.123,381.846,29,594.480,-0.598,103.175,NN
40177,worldshaking,12,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,NaN,989.400,0.534,438.947,30,850.520,0.506,249.358,NaN

In [ ]:
np.log10(KE_ELP['KE_RFreq']) + 1

0        4.392261
1             NaN
2        0.994196
3             NaN
4             NaN
           ...
40476         NaN
40477         NaN
40478         NaN
40479         NaN
40480         NaN
Name: KE_RFreq, Length: 40481, dtype: float64

behvaior data 분석에 사용되지 않

behavior exp data 있는 word 만 추출

In [92]:
# 아래의 값들이 drop 대상.
ELP_LDT_data[ELP_LDT_data['SUBTLWF'] == '#']

,Word,Length,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
10,abasement,9,#,1037.059,0.923,311.845,17,0.53
11,abash,5,#,748.714,0.229,194.366,21,0.68
26,Abe,3,#,820.667,0.075,254.987,33,1.00
29,Abel's,6,#,840.143,0.196,333.080,28,0.82
83,abridgment,10,#,1152.611,0.873,484.354,18,0.60
...,...,...,...,...,...,...,...,...
40415,young's,7,#,844.483,0.038,435.469,29,0.91
40418,youngster's,11,#,763.156,-0.125,260.448,32,0.97
40420,you're,6,#,679.091,-0.288,174.945,33,1.00
40427,you've,6,#,725.903,-0.352,255.048,31,0.91
40429,Yucatan,7,#,813.542,0.310,237.189,24,0.73

In [ ]:
# drop any row which has '#' in the columns_to_check
columns_to_check = ELP_LDT_data.columns.drop(['Word', 'Length', 'I_Mean_Accuracy'])
mask = (ELP_LDT_data[columns_to_check].isin(['#'])).any(axis=1)
ELP_LDT_data = ELP_LDT_data[~mask].reset_index(drop=True)
ELP_LDT_data

,Word,Length,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,20415.270,798.917,-0.013,333.849,24,0.73
1,aah,3,52.710,816.429,0.214,186.029,21,0.62
2,Aaron,5,14.650,736.062,-0.111,289.010,32,0.97
3,aback,5,0.290,796.267,0.110,171.607,15,0.45
4,abacus,6,0.240,964.400,0.655,488.996,15,0.47
...,...,...,...,...,...,...,...,...
35495,zoom,4,3.550,549.758,-0.762,97.649,33,1.00
35496,zooming,7,0.630,709.690,-0.293,283.106,29,0.88
35497,zooms,5,0.060,666.933,-0.476,232.109,30,0.94
35498,zucchini,8,0.960,848.679,0.239,259.819,28,0.85
35499,Zurich,6,2.430,763.000,0.091,184.257,21,0.64

In [94]:
# change columns dtype
ELP_LDT_data['SUBTLWF'] = ELP_LDT_data['SUBTLWF'].astype('float')
ELP_LDT_data['I_Mean_RT'] = ELP_LDT_data['I_Mean_RT'].astype('float')
ELP_LDT_data['I_Zscore'] = ELP_LDT_data['I_Zscore'].astype('float')
ELP_LDT_data['I_SD'] = ELP_LDT_data['I_SD'].astype('float')
ELP_LDT_data['Obs'] = ELP_LDT_data['Obs'].astype('float')

In [100]:
# applying lower to Word 
ELP_LDT_data['Word'] = ELP_LDT_data['Word'].str.lower()

In [101]:
ELP_LDT_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35500 entries, 0 to 35499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Word             35499 non-null  object
 1   Length           35500 non-null  int64
 2   SUBTLWF          35500 non-null  float64
 3   I_Mean_RT        35500 non-null  float64
 4   I_Zscore         35500 non-null  float64
 5   I_SD             35500 non-null  float64
 6   Obs              35500 non-null  float64
 7   I_Mean_Accuracy  35500 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 2.2+ MB

In [96]:
ELP_LDT_data.to_excel(os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT(preprocessed).xlsx'), index=False)

# Merging with KE corpora(depreted): already exist in data files.

In [ ]:
KE_E_Lex_path = os.path.join(corpora_dir, 'merged_corpora', 'CSAT_E_final.xlsx')
KE_E_Lex = pd.read_excel(KE_E_Lex_path)
ELP_LDT_path = os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT(preprocessed).xlsx')
ELP_LDT_data = pd.read_excel(ELP_LDT_path)
KE_E_Lex.head()

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Freq_HAL,SUBTLWF,Freq_KF,CSAT_RFreq,CSAT_only_RFreq,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,POS
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,24675.191037,23843.796660,...,NaN,NaN,NaN,798.917,-0.013,333.849,662.087,-0.323,174.691,minor|NN
1,aah,3,NaN,NaN,NaN,222,2688.21,1.0,NaN,NaN,...,NaN,NaN,NaN,816.429,0.214,186.029,646.400,-0.349,130.445,NaN
2,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,9.867257,2.439762,...,NaN,NaN,NaN,736.062,-0.111,289.010,686.111,-0.203,179.290,NN
3,aback,5,NaN,NaN,NaN,387,14.79,2.0,NaN,NaN,...,NaN,NaN,NaN,796.267,0.110,171.607,596.538,-0.550,89.453,RB
4,abacus,6,NaN,NaN,NaN,513,12.24,NaN,NaN,NaN,...,NaN,NaN,NaN,964.400,0.655,488.996,792.688,0.309,200.186,NN

In [ ]:
# filter the KE words
mask = ~KE_E_Lex['CSAT_Freq'].isna()
KE = KE_E_Lex[mask].reset_index(drop=True)
KE

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Freq_HAL,SUBTLWF,Freq_KF,CSAT_RFreq,CSAT_only_RFreq,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,POS
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,24675.191037,23843.796660,...,NaN,NaN,NaN,798.917,-0.013,333.849,662.087,-0.323,174.691,minor|NN
1,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,9.867257,2.439762,...,NaN,NaN,NaN,736.062,-0.111,289.010,686.111,-0.203,179.290,NN
2,abandon,7,7.0,5.0,2.0,3761,413.10,17.0,9.867257,12.198811,...,2.84,3.73,3.32,695.719,-0.312,220.412,623.963,-0.516,98.251,VB|NN
3,abandoned,9,12.0,5.0,7.0,5160,677.79,25.0,16.915298,12.198811,...,NaN,NaN,NaN,860.774,-0.095,447.558,635.160,-0.487,101.648,VB|JJ
4,abandoning,10,3.0,3.0,NaN,1005,86.19,7.0,4.228825,7.319287,...,NaN,NaN,NaN,740.545,-0.111,288.435,782.783,0.064,218.574,VB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16349,zombies,7,3.0,NaN,3.0,2588,114.75,1.0,4.228825,NaN,...,NaN,NaN,NaN,737.562,-0.148,197.720,645.259,-0.333,92.958,NN
16350,zone,4,19.0,6.0,13.0,17300,1026.12,11.0,26.782555,14.638574,...,4.75,3.78,5.23,577.727,-0.771,165.732,615.357,-0.498,93.202,NN
16351,zones,5,17.0,8.0,9.0,3388,89.76,3.0,23.963339,19.518098,...,NaN,NaN,NaN,605.229,-0.673,153.891,590.080,-0.580,96.943,NN
16352,zoo,3,31.0,21.0,10.0,4317,696.15,9.0,43.697853,51.235008,...,7.00,5.63,6.33,572.562,-0.793,180.819,662.571,-0.198,109.818,NN
16353,zoologist,9,2.0,2.0,NaN,301,12.24,2.0,2.819216,4.879525,...,NaN,NaN,NaN,714.088,-0.118,165.017,732.696,0.190,162.795,NN

# reduce file

In [112]:
KE_E_Lex_path = os.path.join(corpora_dir, 'merged_corpora', 'CSAT_E_final.xlsx')
KE_E_Lex = pd.read_excel(KE_E_Lex_path)
ELP_LDT_path = os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT(preprocessed).xlsx')
ELP_LDT_data = pd.read_excel(ELP_LDT_path)
KE_E_Lex.columns, ELP_LDT_data.columns

(Index(['Word', 'Length', 'CSAT_Freq', 'CSAT_only_Freq', 'Textbook_only_Freq',
        'Freq_HAL', 'SUBTLWF', 'Freq_KF', 'CSAT_RFreq', 'CSAT_only_RFreq',
        'Textbook_only_RFreq', 'RFreq_HAL', 'SUBTLRWF', 'RFreq_KF',
        'Ortho_N_CSAT', 'Ortho_N_CSAT(only)', 'Ortho_N_Textbook(only)',
        'Ortho_N', 'OLD20_CSAT', 'OLD20_CSAT(only)', 'OLD20_Textbook(only)',
        'OLD', 'SUBTLCD', 'Concreteness_Rating', 'Age_Of_Acquisition',
        'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance',
        'I_Mean_RT', 'I_Zscore', 'I_SD', 'I_NMG_Mean_RT', 'I_NMG_Zscore',
        'I_NMG_SD', 'POS'],
       dtype='object'),
 Index(['Word', 'Length', 'SUBTLWF', 'I_Mean_RT', 'I_Zscore', 'I_SD', 'Obs',
        'I_Mean_Accuracy'],
       dtype='object'))

## attach the additional data

In [ ]:
# ELP_LDT_data[['Word', 'Obs', 'I_Mean_Accuracy']]
ELP_LDT_data = pd.merge(KE_E_Lex, ELP_LDT_data[['Word', 'Obs', 'I_Mean_Accuracy']], on='Word', how='left')
ELP_LDT_data

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Freq_HAL,SUBTLWF,Freq_KF,CSAT_RFreq,CSAT_only_RFreq,...,Emotional_Dominance,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,POS,Obs,I_Mean_Accuracy
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,24675.191037,23843.796660,...,NaN,798.917,-0.013,333.849,662.087,-0.323,174.691,minor|NN,24.0,0.73
1,aah,3,NaN,NaN,NaN,222,2688.21,1.0,NaN,NaN,...,NaN,816.429,0.214,186.029,646.400,-0.349,130.445,NaN,21.0,0.62
2,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,9.867257,2.439762,...,NaN,736.062,-0.111,289.010,686.111,-0.203,179.290,NN,NaN,NaN
3,aback,5,NaN,NaN,NaN,387,14.79,2.0,NaN,NaN,...,NaN,796.267,0.110,171.607,596.538,-0.550,89.453,RB,15.0,0.45
4,abacus,6,NaN,NaN,NaN,513,12.24,NaN,NaN,NaN,...,NaN,964.400,0.655,488.996,792.688,0.309,200.186,NN,15.0,0.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zooming,7,NaN,NaN,NaN,523,32.13,1.0,NaN,NaN,...,NaN,709.690,-0.293,283.106,672.370,-0.218,92.353,VB,29.0,0.88
40477,zooms,5,NaN,NaN,NaN,385,3.06,1.0,NaN,NaN,...,NaN,666.933,-0.476,232.109,613.833,-0.552,88.295,VB,30.0,0.94
40478,zucchini,8,NaN,NaN,NaN,314,48.96,NaN,NaN,NaN,...,6.19,848.679,0.239,259.819,756.000,0.207,209.064,NN,28.0,0.85
40479,zurich,6,NaN,NaN,NaN,1770,123.93,2.0,NaN,NaN,...,NaN,763.000,0.091,184.257,822.640,0.213,221.482,NN,NaN,NaN
40480,NaN,4,NaN,NaN,NaN,15410,27.03,13.0,NaN,NaN,...,NaN,703.467,-0.278,168.922,595.741,-0.562,86.852,NN|JJ,30.0,0.88

In [120]:
behavior_cols = ['Word', 'Length', 'CSAT_Freq', 'SUBTLWF', 
                'I_Mean_RT', 'I_Zscore', 'I_SD', 'Obs', 'I_Mean_Accuracy']
ELP_LDT_data = ELP_LDT_data[behavior_cols]
ELP_LDT_data

,Word,Length,CSAT_Freq,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,17505.0,1041178.77,798.917,-0.013,333.849,24.0,0.73
1,aah,3,NaN,2688.21,816.429,0.214,186.029,21.0,0.62
2,aaron,5,7.0,747.15,736.062,-0.111,289.010,NaN,NaN
3,aback,5,NaN,14.79,796.267,0.110,171.607,15.0,0.45
4,abacus,6,NaN,12.24,964.400,0.655,488.996,15.0,0.47
...,...,...,...,...,...,...,...,...,...
40476,zooming,7,NaN,32.13,709.690,-0.293,283.106,29.0,0.88
40477,zooms,5,NaN,3.06,666.933,-0.476,232.109,30.0,0.94
40478,zucchini,8,NaN,48.96,848.679,0.239,259.819,28.0,0.85
40479,zurich,6,NaN,123.93,763.000,0.091,184.257,NaN,NaN
40480,NaN,4,NaN,27.03,703.467,-0.278,168.922,30.0,0.88

In [132]:
mask = ELP_LDT_data[['CSAT_Freq', 'SUBTLWF', 'I_Mean_RT', 'I_Zscore', 'I_SD', 'I_Mean_Accuracy']].isna().any(axis=1)
ELP_LDT_data = ELP_LDT_data[~mask].reset_index(drop=True)
ELP_LDT_data

,Word,Length,CSAT_Freq,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,17505.0,1041178.77,798.917,-0.013,333.849,24.0,0.73
1,abandon,7,7.0,413.10,695.719,-0.312,220.412,32.0,0.97
2,abandoned,9,12.0,677.79,860.774,-0.095,447.558,31.0,0.91
3,abandoning,10,3.0,86.19,740.545,-0.111,288.435,33.0,1.00
4,abandonment,11,2.0,48.96,771.088,-0.002,229.526,34.0,1.00
...,...,...,...,...,...,...,...,...,...
15212,zombies,7,3.0,114.75,737.562,-0.148,197.720,32.0,1.00
15213,zone,4,19.0,1026.12,577.727,-0.771,165.732,33.0,1.00
15214,zones,5,17.0,89.76,605.229,-0.673,153.891,35.0,1.00
15215,zoo,3,31.0,696.15,572.562,-0.793,180.819,32.0,0.97
15216,zoologist,9,2.0,12.24,714.088,-0.118,165.017,34.0,1.00

In [134]:
ELP_LDT_data.rename(columns={'CSAT_Freq': 'KE_Freq'}, inplace=True)
ELP_LDT_data.to_excel(os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT(preprocessed).xlsx'), index=False)

In [135]:
ELP_LDT_data

,Word,Length,KE_Freq,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,17505.0,1041178.77,798.917,-0.013,333.849,24.0,0.73
1,abandon,7,7.0,413.10,695.719,-0.312,220.412,32.0,0.97
2,abandoned,9,12.0,677.79,860.774,-0.095,447.558,31.0,0.91
3,abandoning,10,3.0,86.19,740.545,-0.111,288.435,33.0,1.00
4,abandonment,11,2.0,48.96,771.088,-0.002,229.526,34.0,1.00
...,...,...,...,...,...,...,...,...,...
15212,zombies,7,3.0,114.75,737.562,-0.148,197.720,32.0,1.00
15213,zone,4,19.0,1026.12,577.727,-0.771,165.732,33.0,1.00
15214,zones,5,17.0,89.76,605.229,-0.673,153.891,35.0,1.00
15215,zoo,3,31.0,696.15,572.562,-0.793,180.819,32.0,0.97
15216,zoologist,9,2.0,12.24,714.088,-0.118,165.017,34.0,1.00

In [139]:
ELP_LDT_data['R_SUBTLWF'] = ELP_LDT_data['SUBTLWF'] * (1000. / 5100.)

In [140]:
ELP_LDT_data['R_KE_Freq'] = ELP_LDT_data['KE_Freq'] * (1000. / 83.0)

In [146]:
ELP_LDT_data.sort_values(by='R_SUBTLWF', ascending=False, inplace=True)
ELP_LDT_data.reset_index(drop=True, inplace=True)
ELP_LDT_data

,Word,Length,KE_Freq,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy,R_SUBTLWF,R_KE_Freq
0,you,3,10292.0,2134713.12,615.212,-0.597,152.011,33.0,1.00,418571.2,124000.000000
1,the,3,38303.0,1501908.18,600.194,-0.681,249.144,31.0,0.94,294491.8,461481.927711
2,to,2,21665.0,1156569.84,551.273,-0.786,145.112,33.0,1.00,226778.4,261024.096386
3,a,1,17505.0,1041178.77,798.917,-0.013,333.849,24.0,0.73,204152.7,210903.614458
4,it,2,8679.0,963711.81,566.848,-0.865,194.696,33.0,0.97,188963.1,104566.265060
...,...,...,...,...,...,...,...,...,...,...,...
15212,outweighed,10,1.0,1.02,764.433,-0.026,200.657,30.0,0.91,0.2,12.048193
15213,overcrowd,9,1.0,1.02,782.516,-0.092,346.488,31.0,1.00,0.2,12.048193
15214,fallacious,10,1.0,1.02,819.815,0.335,290.778,27.0,0.84,0.2,12.048193
15215,heritages,9,1.0,1.02,828.690,0.154,322.023,29.0,0.91,0.2,12.048193
15216,approximations,14,1.0,1.02,923.767,0.292,357.855,30.0,0.94,0.2,12.048193

In [143]:
ELP_LDT_data[['R_SUBTLWF', 'R_KE_Freq']].corr()

           R_SUBTLWF  R_KE_Freq
R_SUBTLWF   1.000000   0.843043
R_KE_Freq   0.843043   1.000000

In [150]:
ELP_LDT_data.shape[0]

15217

In [156]:
ELP_LDT_data[['R_SUBTLWF', 'R_KE_Freq']][:int(ELP_LDT_data.shape[0]/2)].corr()

           R_SUBTLWF  R_KE_Freq
R_SUBTLWF   1.000000   0.842008
R_KE_Freq   0.842008   1.000000

In [157]:
ELP_LDT_data[['R_SUBTLWF', 'R_KE_Freq']][:int(ELP_LDT_data.shape[0]/2)].corr(method='spearman')

           R_SUBTLWF  R_KE_Freq
R_SUBTLWF   1.000000   0.628804
R_KE_Freq   0.628804   1.000000

In [158]:
ELP_LDT_data[['R_SUBTLWF', 'R_KE_Freq']][int(ELP_LDT_data.shape[0]/2):].corr()

           R_SUBTLWF  R_KE_Freq
R_SUBTLWF   1.000000   0.269901
R_KE_Freq   0.269901   1.000000

In [159]:
ELP_LDT_data[['R_SUBTLWF', 'R_KE_Freq']][int(ELP_LDT_data.shape[0]/2):].corr(method='spearman')

           R_SUBTLWF  R_KE_Freq
R_SUBTLWF   1.000000   0.352928
R_KE_Freq   0.352928   1.000000