# Corpus Merging.

## CSAT 만들기

CSAT의 경우, 자체적인 POS 값들 달기 애매하기 때문에 E-lexicon proj에서 제공하는 POS 값을 우선적으로 가져와서 붙여 넣자. 아마 대부분 있지 않을까?

### Module Import

In [1]:
import pandas as pd # 데이터 처리
import numpy as np # 데이터 처리
import seaborn as sns # 데이터 시각화
from tqdm import tqdm # 데이터 처리
import re # 정규식으로 특수기호 및 char 처리
import json # 데이터 가공 후 저장할 형식
from typing import Any, Dict, List  # python data-type 정의
from pathlib import Path # 파일 경로 처리
import os # 파일 경로 및 처리
from json_handler import JsonFileHandler
from preprocessor import Preprocessor, TargetCorpusPreprocessor

### file path setting

In [4]:
# 파일 경로 확인.
proj_path = os.path.dirname(os.path.dirname(Path.cwd()))
corpora_dir = os.path.join(proj_path, 'Corpora')
CSAT_json_path = save_path = os.path.join(corpora_dir, 'CSAT-latest')

# 파일 경로 유효성 확인.
if not os.path.exists(proj_path):
    raise FileNotFoundError(f"Project path not found at {proj_path}")
if not os.path.exists(CSAT_json_path):
    raise FileNotFoundError(f"CSAT json path not found at {CSAT_json_path}")
if not any(file.endswith('.json') for file in os.listdir(CSAT_json_path)):
    raise FileExistsError(f"Any .json file doesn't exist in {CSAT_json_path}")
print("All file paths are valid.")

All file paths are valid.

### Utils: generate_word_list
중복을 허용하여 단어를 extend 한 list 생성.
이후 pandas 다른 method(ex: value_count)를 사용해서 빈도수 계산.

In [17]:
def generate_word_list(document_list: list, document_dir: str):
    # article 별 단어 분석.
    word_list = []   # word 정보를 담을 리스트
    json_handler = JsonFileHandler()

    for document_name in document_list: # corpus에서 하나의 json 파일을 가져와서
        document = json_handler.load_data(os.path.join(document_dir, document_name))  # 하나의 json 파일 내에 있는 모든 파일을 가져옴.

        if isinstance(document, list):   # 한 json 내에 여러 obj가 있는 경우, 
            for sentence in document:  # json 파일 내 있는 여러 문장들 수 
                word_list.extend(sentence['tokens'])
        else:   # 한 json 내에 하나의 obj가 있는 경우, 
            word_list.extend(document['tokens'])   

    return word_list

### CSAT(only): 수능 + 모의고사

In [5]:
json_handler = JsonFileHandler()
CSAT_path = os.path.join(corpora_dir, 'CSAT-latest')
corpus_list = os.listdir(CSAT_path)
corpus_list = [file for file in corpus_list if file.endswith('.json')]
reading_corpus = [file for file in corpus_list if 'reading' in file]
listening_corpus = [file for file in corpus_list if 'listening' in file]

len(reading_corpus), len(listening_corpus)

(52, 49)

In [7]:
listening_word_list = generate_word_list(listening_corpus, CSAT_path)
reading_word_list = generate_word_list(reading_corpus, CSAT_path)
CSAT_only_word_list = pd.Series(listening_word_list + reading_word_list)

In [8]:
CSAT_only_word_list.shape

(482265,)

In [9]:
CSAT_only_word_list.value_counts()

.            32877
,            21944
the          21540
to           12665
of           10010
             ...
arabian          1
sapphire         1
sandstone        1
khyber           1
doubly           1
Name: count, Length: 17438, dtype: int64

In [10]:
CSAT_only_word_list_df = CSAT_only_word_list.value_counts().to_frame().reset_index().rename(columns={'index': 'Word', 'count': 'Freq'})
CSAT_only_word_list_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_only.xlsx'), index=False)
CSAT_only_word_list_df

            Word   Freq
0              .  32877
1              ,  21944
2            the  21540
3             to  12665
4             of  10010
...          ...    ...
17433    arabian      1
17434   sapphire      1
17435  sandstone      1
17436     khyber      1
17437     doubly      1

[17438 rows x 2 columns]

### textbook(only)

In [11]:
json_handler = JsonFileHandler()
CSAT_path = os.path.join(corpora_dir, 'CSAT-latest')
corpus_list = os.listdir(CSAT_path)
corpus_list = [file for file in corpus_list if file.endswith('.json')]
textbook_corpus = [file for file in corpus_list if 'textbook' in file]

len(textbook_corpus)

71

In [12]:
textbook_word_list = generate_word_list(textbook_corpus, CSAT_path)
textbook_only_word_list = pd.Series(textbook_word_list)

In [13]:
textbook_only_word_list.shape

(352760,)

In [14]:
textbook_only_word_list.value_counts()

.                 22088
the               16763
,                 16722
to                 9000
and                7844
                  ...
elegance              1
geographically        1
breakfasts            1
whiteboard            1
maturity              1
Name: count, Length: 14822, dtype: int64

In [15]:
textbook_only_word_list_df = textbook_only_word_list.value_counts().to_frame().reset_index().rename(columns={'index': 'Word', 'count': 'Freq'})
textbook_only_word_list_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'textbook_only.xlsx'), index=False)
textbook_only_word_list_df

                 Word   Freq
0                   .  22088
1                 the  16763
2                   ,  16722
3                  to   9000
4                 and   7844
...               ...    ...
14817        elegance      1
14818  geographically      1
14819      breakfasts      1
14820      whiteboard      1
14821        maturity      1

[14822 rows x 2 columns]

### CSAT Total

In [4]:
json_handler = JsonFileHandler()
CSAT_path = os.path.join(corpora_dir, 'CSAT-latest')
corpus_list = os.listdir(CSAT_path)
corpus_list = [file for file in corpus_list if file.endswith('.json')]
reading_corpus = [file for file in corpus_list if 'reading' in file]
listening_corpus = [file for file in corpus_list if 'listening' in file]
textbook_corpus = [file for file in corpus_list if 'textbook' in file]

len(reading_corpus), len(listening_corpus), len(textbook_corpus)

(52, 49, 71)

In [7]:
listening_word_list = generate_word_list(listening_corpus, CSAT_path)
reading_word_list = generate_word_list(reading_corpus, CSAT_path)
textbook_word_list = generate_word_list(textbook_corpus, CSAT_path)
CSAT_word_list = pd.Series(listening_word_list + reading_word_list + textbook_word_list)

In [8]:
CSAT_word_list.shape

(835025,)

In [9]:
CSAT_word_list.value_counts()

.             54965
,             38666
the           38303
to            21665
a             17505
              ...
tersely           1
trimly            1
imbricate         1
sepals            1
regretting        1
Name: count, Length: 22147, dtype: int64

In [10]:
CSAT_word_list_df = CSAT_word_list.value_counts().to_frame().reset_index().rename(columns={'index': 'Word', 'count': 'Freq'})
#CSAT_word_list_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT.xlsx'), index=False)
CSAT_word_list_df

             Word   Freq
0               .  54965
1               ,  38666
2             the  38303
3              to  21665
4               a  17505
...           ...    ...
22142     tersely      1
22143      trimly      1
22144   imbricate      1
22145      sepals      1
22146  regretting      1

[22147 rows x 2 columns]

## E-lexicon proj

E-lexicon proj를 보면, a의 orthographic N이 1이다. 즉, b,c,d,e 같이 치환된 케이스 중 비단어는 제외했다는 말이니, CSAT도 그대로 사용하기는 무리. 따라서 E-lexicon이랑 intersection을 먼저 시켜봐야 할 듯.

In [7]:
E_lexicon_proj_path = os.path.join(corpora_dir, 'E-lexicon-proj')

In [9]:
E_lexicon_df = pd.read_csv(os.path.join(E_lexicon_proj_path, 'English Lexicon Project Items.csv'))
E_lexicon_df.head()

,Word,Length,Freq_KF,Freq_HAL,SUBTLWF,SUBTLCD,Ortho_N,Freq_N,OLD,Concreteness_Rating,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,POS,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD
0,a,1,"23,237","10,610,626","20,415.270",99.930,1,15.8,1.450,1.460,...,#,#,#,minor|NN,798.917,-0.013,333.849,662.087,-0.323,174.691
1,aah,3,1,222,52.710,7.560,2,7.4,1.850,#,...,#,#,#,#,816.429,0.214,186.029,646.400,-0.349,130.445
2,Aaron,5,7,"10,806",14.650,1.930,3,7.4,1.850,#,...,#,#,#,NN,736.062,-0.111,289.010,686.111,-0.203,179.290
3,aback,5,2,387,0.290,0.180,0,#,1.950,1.650,...,#,#,#,RB,796.267,0.110,171.607,596.538,-0.550,89.453
4,abacus,6,#,513,0.240,0.120,0,#,2.900,4.520,...,#,#,#,NN,964.400,0.655,488.996,792.688,0.309,200.186

In [10]:
# null이라는 단어가 있는데, type 지정을 안 해주면 null 값으로 분류됨.
E_lexicon_df['Word'] = E_lexicon_df['Word'].astype(str)
E_lexicon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Word                 40481 non-null  object
 1   Length               40481 non-null  int64
 2   Freq_KF              40481 non-null  object
 3   Freq_HAL             40481 non-null  object
 4   SUBTLWF              40481 non-null  object
 5   SUBTLCD              40481 non-null  object
 6   Ortho_N              40481 non-null  int64
 7   Freq_N               40481 non-null  object
 8   OLD                  40481 non-null  object
 9   Concreteness_Rating  40481 non-null  object
 10  Age_Of_Acquisition   40481 non-null  object
 11  Emotional_Valence    40481 non-null  object
 12  Emotional_Arousal    40481 non-null  object
 13  Emotional_Dominance  40481 non-null  object
 14  POS                  40481 non-null  object
 15  I_Mean_RT            40481 non-null  object
 16  I_Zscore             40481 non-null  object
 17  I_SD                 40481 non-null  object
 18  I_NMG_Mean_RT        40481 non-null  object
 19  I_NMG_Zscore         40481 non-null  float64
 20  I_NMG_SD             40481 non-null  object
dtypes: float64(1), int64(2), object(18)
memory usage: 6.5+ MB

E-lexicon proj에서도 Word는 lower 적용.

In [11]:
E_lexicon_df['Word'] = E_lexicon_df['Word'].str.lower()
E_lexicon_df.head()

,Word,Length,Freq_KF,Freq_HAL,SUBTLWF,SUBTLCD,Ortho_N,Freq_N,OLD,Concreteness_Rating,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,POS,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD
0,a,1,"23,237","10,610,626","20,415.270",99.930,1,15.8,1.450,1.460,...,#,#,#,minor|NN,798.917,-0.013,333.849,662.087,-0.323,174.691
1,aah,3,1,222,52.710,7.560,2,7.4,1.850,#,...,#,#,#,#,816.429,0.214,186.029,646.400,-0.349,130.445
2,aaron,5,7,"10,806",14.650,1.930,3,7.4,1.850,#,...,#,#,#,NN,736.062,-0.111,289.010,686.111,-0.203,179.290
3,aback,5,2,387,0.290,0.180,0,#,1.950,1.650,...,#,#,#,RB,796.267,0.110,171.607,596.538,-0.550,89.453
4,abacus,6,#,513,0.240,0.120,0,#,2.900,4.520,...,#,#,#,NN,964.400,0.655,488.996,792.688,0.309,200.186

In [12]:
E_lexicon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Word                 40481 non-null  object
 1   Length               40481 non-null  int64
 2   Freq_KF              40481 non-null  object
 3   Freq_HAL             40481 non-null  object
 4   SUBTLWF              40481 non-null  object
 5   SUBTLCD              40481 non-null  object
 6   Ortho_N              40481 non-null  int64
 7   Freq_N               40481 non-null  object
 8   OLD                  40481 non-null  object
 9   Concreteness_Rating  40481 non-null  object
 10  Age_Of_Acquisition   40481 non-null  object
 11  Emotional_Valence    40481 non-null  object
 12  Emotional_Arousal    40481 non-null  object
 13  Emotional_Dominance  40481 non-null  object
 14  POS                  40481 non-null  object
 15  I_Mean_RT            40481 non-null  object
 16  I_Zscore             40481 non-null  object
 17  I_SD                 40481 non-null  object
 18  I_NMG_Mean_RT        40481 non-null  object
 19  I_NMG_Zscore         40481 non-null  float64
 20  I_NMG_SD             40481 non-null  object
dtypes: float64(1), int64(2), object(18)
memory usage: 6.5+ MB

In [13]:
from preprocessor import TargetCorpusPreprocessor

E_lexicon_df = TargetCorpusPreprocessor(E_lexicon_df).preprocess()
E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'E_lexicon_preprocessed.xlsx'), index=False)

Cleaning information col by col:   0%|          | 0/21 [00:00<?, ?it/s]

Freq_KF

Cleaning information col by col:  14%|█▍        | 3/21 [00:03<00:18,  1.02s/it]

Freq_HAL
SUBTLWF

Cleaning information col by col:  24%|██▍       | 5/21 [00:04<00:14,  1.10it/s]

SUBTLCD

Cleaning information col by col:  29%|██▊       | 6/21 [00:06<00:16,  1.08s/it]

Freq_N

Cleaning information col by col:  43%|████▎     | 9/21 [00:18<00:30,  2.50s/it]

OLD
Concreteness_Rating

Cleaning information col by col:  48%|████▊     | 10/21 [00:25<00:39,  3.62s/it]

Age_Of_Acquisition

Cleaning information col by col:  52%|█████▏    | 11/21 [00:29<00:36,  3.61s/it]

Emotional_Valence

Cleaning information col by col:  57%|█████▋    | 12/21 [00:42<00:57,  6.39s/it]

Emotional_Arousal

Cleaning information col by col:  62%|██████▏   | 13/21 [00:56<01:07,  8.48s/it]

Emotional_Dominance

Cleaning information col by col:  67%|██████▋   | 14/21 [01:10<01:09,  9.96s/it]

POS

Cleaning information col by col: 100%|██████████| 21/21 [01:10<00:00,  3.37s/it]

I_Mean_RT
I_Zscore
I_SD
I_NMG_Mean_RT
I_NMG_SD

In [14]:
E_lexicon_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'E_lexicon_preprocessed.xlsx'))
E_lexicon_df

,Word,Length,Freq_KF,Freq_HAL,SUBTLWF,SUBTLCD,Ortho_N,Freq_N,OLD,Concreteness_Rating,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,POS,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD
0,a,1,23237.0,10610626,20415.27,99.93,1,15.8,1.45,1.46,...,NaN,NaN,NaN,minor|NN,798.917,-0.013,333.849,662.087,-0.323,174.691
1,aah,3,1.0,222,52.71,7.56,2,7.4,1.85,NaN,...,NaN,NaN,NaN,NaN,816.429,0.214,186.029,646.400,-0.349,130.445
2,aaron,5,7.0,10806,14.65,1.93,3,7.4,1.85,NaN,...,NaN,NaN,NaN,NN,736.062,-0.111,289.010,686.111,-0.203,179.290
3,aback,5,2.0,387,0.29,0.18,0,NaN,1.95,1.65,...,NaN,NaN,NaN,RB,796.267,0.110,171.607,596.538,-0.550,89.453
4,abacus,6,NaN,513,0.24,0.12,0,NaN,2.90,4.52,...,NaN,NaN,NaN,NN,964.400,0.655,488.996,792.688,0.309,200.186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zoom,4,NaN,4920,3.55,1.29,4,9.2,1.70,3.10,...,5.86,5.68,5.90,VB|NN,549.758,-0.762,97.649,639.857,-0.441,108.340
40477,zooming,7,1.0,523,0.63,0.31,3,5.8,1.85,NaN,...,NaN,NaN,NaN,VB,709.690,-0.293,283.106,672.370,-0.218,92.353
40478,zooms,5,1.0,385,0.06,0.04,3,6.7,1.80,NaN,...,NaN,NaN,NaN,VB,666.933,-0.476,232.109,613.833,-0.552,88.295
40479,zucchini,8,NaN,314,0.96,0.25,0,NaN,3.75,4.87,...,6.30,4.18,6.19,NN,848.679,0.239,259.819,756.000,0.207,209.064
40480,zurich,6,2.0,1770,2.43,0.74,0,NaN,2.80,NaN,...,NaN,NaN,NaN,NN,763.000,0.091,184.257,822.640,0.213,221.482

### CSAT_edit

In [34]:
CSAT_only_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_only.xlsx'))
textbook_only_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'textbook_only.xlsx'))
CSAT_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT.xlsx'))

# overlap 1562개
CSAT_df.shape, CSAT_only_df.shape,textbook_only_df.shape

((22147, 2), (17438, 2), (14822, 2))

각각 E-lexicon이랑 합치고 POS 달기

In [35]:
CSAT_only_POS_df = pd.merge(CSAT_only_df, E_lexicon_df, on='Word', how='inner')[['Word', 'Freq', 'POS']]
CSAT_only_POS_df = CSAT_only_POS_df.dropna(subset=['POS']).reset_index(drop=True)
CSAT_only_POS_df

            Word   Freq       POS
0            the  21540     minor
1             to  12665     minor
2             of  10010     minor
3              a   9773  minor|NN
4            and   8974     minor
...          ...    ...       ...
14004   fortress      1        NN
14005    arabian      1     NN|JJ
14006   sapphire      1        NN
14007  sandstone      1        NN
14008     doubly      1        RB

[14009 rows x 3 columns]

In [36]:
textbook_only_POS_df = pd.merge(textbook_only_df, E_lexicon_df, on='Word', how='inner')[['Word', 'Freq', 'POS']]
textbook_only_POS_df = textbook_only_POS_df.dropna(subset=['POS']).reset_index(drop=True)
textbook_only_POS_df

                 Word   Freq       POS
0                 the  16763     minor
1                  to   9000     minor
2                 and   7844     minor
3                   a   7732  minor|NN
4                  of   7161     minor
...               ...    ...       ...
11796        deathbed      1        NN
11797        elegance      1        NN
11798  geographically      1        RB
11799      breakfasts      1     NN|VB
11800        maturity      1        NN

[11801 rows x 3 columns]

In [37]:
CSAT_POS_df = pd.merge(CSAT_df, E_lexicon_df, on='Word', how='inner')[['Word', 'Freq', 'POS']]
CSAT_POS_df = CSAT_POS_df.dropna(subset=['POS']).reset_index(drop=True)
CSAT_POS_df

            Word   Freq       POS
0            the  38303     minor
1             to  21665     minor
2              a  17505  minor|NN
3             of  17171     minor
4            and  16818     minor
...          ...    ...       ...
16349      vomit      1     VB|NN
16350  surpluses      1        NN
16351   resented      1     VB|JJ
16352     winded      1     JJ|VB
16353    tersely      1        RB

[16354 rows x 3 columns]

### 그렇다면 차집합도 볼만 하겠지?

In [38]:
E_lexicon_df

,Word,Length,Freq_HAL,Log_Freq_HAL,SUBTLWF,LgSUBTLWF,SUBTLCD,LgSUBTLCD,Ortho_N,OLD,POS
0,a,1,10610626,16.177,20415.27,6.018,99.93,3.923,1,1.45,minor|NN
1,aah,3,222,5.403,52.71,3.430,7.56,2.803,2,1.85,NaN
2,aaron,5,10806,9.288,14.65,2.874,1.93,2.212,3,1.85,NN
3,aback,5,387,5.958,0.29,1.204,0.18,1.204,0,1.95,RB
4,abacus,6,513,6.240,0.24,1.114,0.12,1.041,0,2.90,NN
...,...,...,...,...,...,...,...,...,...,...,...
40476,zoom,4,4920,8.501,3.55,2.260,1.29,2.037,4,1.70,VB|NN
40477,zooming,7,523,6.260,0.63,1.518,0.31,1.431,3,1.85,VB
40478,zooms,5,385,5.953,0.06,0.602,0.04,0.602,3,1.80,VB
40479,zucchini,8,314,5.749,0.96,1.699,0.25,1.342,0,3.75,NN
40480,zurich,6,1770,7.479,2.43,2.097,0.74,1.799,0,2.80,NN

In [26]:
E_lexicon_df[E_lexicon_df['POS'].isna() == True]

,Word,Length,Freq_HAL,Log_Freq_HAL,SUBTLWF,LgSUBTLWF,SUBTLCD,LgSUBTLCD,Ortho_N,OLD,POS
1,aah,3,222,5.403,52.71,3.430,7.56,2.803,2,1.85,NaN
361,actor's,7,363,5.894,NaN,NaN,NaN,NaN,0,NaN,NaN
708,agamemnon's,11,16,2.773,NaN,NaN,NaN,NaN,0,NaN,NaN
812,airbladder,10,0,0.000,NaN,NaN,NaN,NaN,0,4.30,NaN
814,airbrake,8,22,3.091,NaN,NaN,NaN,NaN,0,3.45,NaN
...,...,...,...,...,...,...,...,...,...,...,...
40198,worshiped,9,331,5.802,0.43,1.362,0.26,1.362,0,3.30,NaN
40299,wyndham's,9,12,2.485,NaN,NaN,NaN,NaN,0,NaN,NaN
40310,yachters,8,2,0.693,NaN,NaN,NaN,NaN,0,2.95,NaN
40403,yorker's,8,16,2.773,NaN,NaN,NaN,NaN,1,NaN,NaN
40418,youngster's,11,41,3.714,NaN,NaN,NaN,NaN,0,NaN,NaN

In [27]:
CSAT_only_diff_E_lexicon_df = pd.merge(CSAT_only_df, E_lexicon_df, on='Word', how='outer', indicator=True)[['Word', 'Freq', 'POS', '_merge']]
#CSAT_only_minus_E_lexicon_df = CSAT_only_minus_E_lexicon_df.dropna(subset=['POS']).reset_index(drop=True)
CSAT_only_diff_E_lexicon_df = CSAT_only_diff_E_lexicon_df[CSAT_only_diff_E_lexicon_df['_merge'] != 'both'].reset_index(drop=True)
CSAT_only_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_only_diff_E_lexicon.xlsx'), index=False)
CSAT_only_diff_E_lexicon_df

           Word  Freq    POS      _merge
0             '  31.0    NaN   left_only
1            ''   1.0    NaN   left_only
2      'bambuco   1.0    NaN   left_only
3         'best   1.0    NaN   left_only
4       'cumbia   1.0    NaN   left_only
...         ...   ...    ...         ...
29868  zucchini   NaN     NN  right_only
29869  zukerman   3.0    NaN   left_only
29870     zulus   1.0    NaN   left_only
29871    zurich   NaN     NN  right_only
29872       NaN   NaN  NN|JJ  right_only

[29873 rows x 4 columns]

In [28]:
textbook_only_diff_E_lexicon_df = pd.merge(textbook_only_df, E_lexicon_df, on='Word', how='outer', indicator=True)[['Word', 'Freq', 'POS', '_merge']]
#CSAT_only_minus_E_lexicon_df = CSAT_only_minus_E_lexicon_df.dropna(subset=['POS']).reset_index(drop=True)
textbook_only_diff_E_lexicon_df = textbook_only_diff_E_lexicon_df[textbook_only_diff_E_lexicon_df['_merge'] != 'both'].reset_index(drop=True)
textbook_only_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'textbook_only_diff_E_lexicon.xlsx'), index=False)
textbook_only_diff_E_lexicon_df

           Word  Freq    POS      _merge
0             '   8.0    NaN   left_only
1            'd   2.0    NaN   left_only
2            'i   1.0    NaN   left_only
3           'll   1.0    NaN   left_only
4            't   1.0    NaN   left_only
...         ...   ...    ...         ...
31682     zquez   2.0    NaN   left_only
31683  zucchini   NaN     NN  right_only
31684      zulu   3.0    NaN   left_only
31685    zurich   NaN     NN  right_only
31686       NaN   NaN  NN|JJ  right_only

[31687 rows x 4 columns]

In [29]:
CSAT_diff_E_lexicon_df = pd.merge(CSAT_df, E_lexicon_df, on='Word', how='outer', indicator=True)[['Word', 'Freq', 'POS', '_merge']]
#CSAT_minus_E_lexicon_df = CSAT_minus_E_lexicon_df.dropna(subset=['POS']).reset_index(drop=True)
CSAT_diff_E_lexicon_df = CSAT_diff_E_lexicon_df[CSAT_diff_E_lexicon_df['_merge'] != 'both'].reset_index(drop=True)
CSAT_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_diff_E_lexicon.xlsx'), index=False)
CSAT_diff_E_lexicon_df

           Word  Freq    POS      _merge
0             '  39.0    NaN   left_only
1            ''   1.0    NaN   left_only
2      'bambuco   1.0    NaN   left_only
3         'best   1.0    NaN   left_only
4       'cumbia   1.0    NaN   left_only
...         ...   ...    ...         ...
29877  zukerman   3.0    NaN   left_only
29878      zulu   3.0    NaN   left_only
29879     zulus   1.0    NaN   left_only
29880    zurich   NaN     NN  right_only
29881       NaN   NaN  NN|JJ  right_only

[29882 rows x 4 columns]

In [30]:
CSAT_only_diff_E_lexicon_df = CSAT_only_diff_E_lexicon_df.drop(columns=['POS', '_merge'])
CSAT_only_diff_E_lexicon_df.columns = ['Word', 'CSAT_only_Freq']
CSAT_only_diff_E_lexicon_df

           Word  CSAT_only_Freq
0             '            31.0
1            ''             1.0
2      'bambuco             1.0
3         'best             1.0
4       'cumbia             1.0
...         ...             ...
29868  zucchini             NaN
29869  zukerman             3.0
29870     zulus             1.0
29871    zurich             NaN
29872       NaN             NaN

[29873 rows x 2 columns]

In [31]:
textbook_only_diff_E_lexicon_df = textbook_only_diff_E_lexicon_df.drop(columns=['POS', '_merge'])
textbook_only_diff_E_lexicon_df.columns = ['Word', 'textbook_only_Freq']
textbook_only_diff_E_lexicon_df

           Word  textbook_only_Freq
0             '                 8.0
1            'd                 2.0
2            'i                 1.0
3           'll                 1.0
4            't                 1.0
...         ...                 ...
31682     zquez                 2.0
31683  zucchini                 NaN
31684      zulu                 3.0
31685    zurich                 NaN
31686       NaN                 NaN

[31687 rows x 2 columns]

In [32]:
CSAT_diff_E_lexicon_df = CSAT_diff_E_lexicon_df.drop(columns=['POS'])
CSAT_diff_E_lexicon_df.columns = ['Word', 'CSAT_Freq', '_merge']
CSAT_diff_E_lexicon_df

           Word  CSAT_Freq      _merge
0             '       39.0   left_only
1            ''        1.0   left_only
2      'bambuco        1.0   left_only
3         'best        1.0   left_only
4       'cumbia        1.0   left_only
...         ...        ...         ...
29877  zukerman        3.0   left_only
29878      zulu        3.0   left_only
29879     zulus        1.0   left_only
29880    zurich        NaN  right_only
29881       NaN        NaN  right_only

[29882 rows x 3 columns]

In [33]:
CSAT_diff_E_lexicon_df = pd.merge(pd.merge(CSAT_only_diff_E_lexicon_df, textbook_only_diff_E_lexicon_df, on='Word', how='outer'), CSAT_diff_E_lexicon_df, on='Word', how='outer')
CSAT_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_diff_E_lexicon.xlsx'), index=False)
CSAT_diff_E_lexicon_df

           Word  CSAT_only_Freq  textbook_only_Freq  CSAT_Freq      _merge
0             '            31.0                 8.0       39.0   left_only
1            ''             1.0                 NaN        1.0   left_only
2      'bambuco             1.0                 NaN        1.0   left_only
3         'best             1.0                 NaN        1.0   left_only
4       'cumbia             1.0                 NaN        1.0   left_only
...         ...             ...                 ...        ...         ...
36792  zukerman             3.0                 NaN        3.0   left_only
36793      zulu             NaN                 3.0        3.0   left_only
36794     zulus             1.0                 NaN        1.0   left_only
36795    zurich             NaN                 NaN        NaN  right_only
36796       NaN             NaN                 NaN        NaN  right_only

[36797 rows x 5 columns]

In [12]:
import requests
from nltk.corpus import wordnet
import nltk
nltk.download('wordnet')

def check_word_exists(word):
    
    # 2. WordNet으로 확인
    if wordnet.synsets(word):
        return True
    
    
    # 3. Free Dictionary API로 확인
    try:
        print(f"Checking {word}...")
        response = requests.get(f"https://api.dictionaryapi.dev/api/v2/entries/en/{word}", timeout=5)
        if response.status_code == 200:
            return True
        else:
            return False
    except:
        return False

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [13]:
check_word_exists('zookeeper')

Checking zookeeper...

True

In [ ]:
is_exit_list = []
for i, item in tqdm(enumerate(CSAT_diff_E_lexicon_df['Word'])):
    if check_word_exists(item) == True:
        is_exit_list.append(True)
    else:
        is_exit_list.append(False)
CSAT_diff_E_lexicon_df['is_exist'] = is_exit_list

CSAT_diff_E_lexicon_df[CSAT_diff_E_lexicon_df['is_exist'] == False]

0it [00:00, ?it/s]

Checking '...

1it [00:25, 25.78s/it]

Checking ''...

2it [00:56, 28.49s/it]

Checking 'bambuco...

3it [01:26, 29.39s/it]

Checking 'best...

4it [01:57, 29.83s/it]

Checking 'cumbia...

5it [02:27, 30.02s/it]

Checking 'd...

6it [02:58, 30.35s/it]

Checking 'fragile...

7it [03:28, 30.37s/it]

Checking 'hand...

8it [03:59, 30.52s/it]

Checking 'i...

9it [04:30, 30.51s/it]

Checking 'laughmobile...

10it [05:00, 30.47s/it]

Checking 'leaking...

11it [05:31, 30.56s/it]

Checking 'll...

12it [06:02, 30.63s/it]

Checking 'm...

13it [06:32, 30.57s/it]

Checking 'maybe...

14it [07:02, 30.51s/it]

Checking 'pause...

15it [07:33, 30.47s/it]

Checking 're...

16it [08:03, 30.47s/it]

Checking 'rich...

17it [08:34, 30.46s/it]

Checking 't...

18it [09:04, 30.51s/it]

Checking 'truth...

19it [09:35, 30.58s/it]

Checking 've...

20it [10:06, 30.63s/it]

Checking 'why...

21it [10:37, 30.66s/it]

Checking 'wilderness...

22it [11:07, 30.72s/it]

Checking ,...

23it [11:38, 30.56s/it]

Checking ....

24it [12:08, 30.63s/it]

Checking abab...

27it [12:39, 19.16s/it]

Checking ababababababab...

28it [13:10, 21.61s/it]

Checking abdi...

47it [13:41,  4.59s/it]

Checking abdul...

53it [14:11,  4.73s/it]

Checking abe...

54it [14:42,  6.35s/it]

Checking abebe...

55it [15:13,  8.33s/it]

Checking abel's...

58it [15:43,  8.80s/it]

Checking abigail...

71it [16:14,  4.84s/it]

Checking ableshipping...

74it [16:45,  5.75s/it]

Checking abu...

152it [17:16,  1.13s/it]

Checking aburke...

155it [17:46,  1.55s/it]

Checking academi...

165it [18:17,  1.81s/it]

Checking accessors...

193it [18:47,  1.51s/it]

Checking accidently...

195it [19:18,  2.07s/it]

Checking achieveddraining...

254it [19:48,  1.09s/it]

Checking achoo...

258it [20:19,  1.47s/it]

Checking acidmost...

264it [20:49,  1.87s/it]

Checking activites...

308it [21:20,  1.24s/it]

Checking actor's...

309it [21:51,  1.75s/it]

Checking ada's...

322it [22:22,  1.90s/it]

Checking adaily...

325it [22:53,  2.52s/it]

Checking adam's...

326it [23:23,  3.46s/it]

Checking adaptively...

334it [23:54,  3.55s/it]

Checking addae...

336it [24:24,  4.63s/it]

Checking adele...

352it [24:55,  3.25s/it]

Checking adia...

367it [25:26,  2.76s/it]

Checking adirondack...

371it [25:56,  3.42s/it]

Checking adlai...

397it [26:27,  2.18s/it]

Checking admin...

398it [26:58,  3.03s/it]

Checking administration's...

403it [27:29,  3.58s/it]

Checking adolescent's...

430it [28:00,  2.18s/it]

Checking adolf...

432it [28:04,  2.16s/it]

Checking adrianna...

In [ ]:
CSAT_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_diff_E_lexicon.xlsx'), index=False)

add Ortho_N, OLD20

In [39]:
from neighborhood import orthographic_N, OLD20

lexicon = CSAT_POS_df['Word'].to_list() 

CSAT_POS_df['Ortho_N_CSAT'] = CSAT_POS_df['Word'].apply(lambda x: orthographic_N(x, lexicon))
CSAT_POS_df['OLD20_CSAT'] = CSAT_POS_df['Word'].apply(lambda x: OLD20(x, lexicon))
CSAT_POS_df

            Word   Freq       POS  Ortho_N_CSAT  OLD20_CSAT
0            the  38303     minor             3        1.55
1             to  21665     minor             6        1.20
2              a  17505  minor|NN             1        1.45
3             of  17171     minor             6        1.55
4            and  16818     minor             6        1.20
...          ...    ...       ...           ...         ...
16349      vomit      1     VB|NN             0        2.45
16350  surpluses      1        NN             0        3.30
16351   resented      1     VB|JJ             0        2.15
16352     winded      1     JJ|VB             3        1.75
16353    tersely      1        RB             0        2.70

[16354 rows x 5 columns]

In [40]:
lexicon = CSAT_only_POS_df['Word'].to_list() 

CSAT_only_POS_df['Ortho_N_CSAT(only)'] = CSAT_only_POS_df['Word'].apply(lambda x: orthographic_N(x, lexicon))
CSAT_only_POS_df['OLD20_CSAT(only)'] = CSAT_only_POS_df['Word'].apply(lambda x: OLD20(x, lexicon))
CSAT_only_POS_df

            Word   Freq       POS  Ortho_N_CSAT(only)  OLD20_CSAT(only)
0            the  21540     minor                   2              1.60
1             to  12665     minor                   4              1.35
2             of  10010     minor                   5              1.60
3              a   9773  minor|NN                   1              1.45
4            and   8974     minor                   6              1.25
...          ...    ...       ...                 ...               ...
14004   fortress      1        NN                   0              2.80
14005    arabian      1     NN|JJ                   0              2.75
14006   sapphire      1        NN                   0              3.60
14007  sandstone      1        NN                   0              3.75
14008     doubly      1        RB                   1              2.55

[14009 rows x 5 columns]

In [41]:
lexicon = textbook_only_POS_df['Word'].to_list() 

textbook_only_POS_df['Ortho_N_Textbook'] = textbook_only_POS_df['Word'].apply(lambda x: orthographic_N(x, lexicon))
textbook_only_POS_df['OLD20_Textbook'] = textbook_only_POS_df['Word'].apply(lambda x: OLD20(x, lexicon))
textbook_only_POS_df

                 Word   Freq       POS  Ortho_N_Textbook  OLD20_Textbook
0                 the  16763     minor                 3            1.55
1                  to   9000     minor                 6            1.25
2                 and   7844     minor                 6            1.20
3                   a   7732  minor|NN                 1            1.45
4                  of   7161     minor                 6            1.55
...               ...    ...       ...               ...             ...
11796        deathbed      1        NN                 0            3.10
11797        elegance      1        NN                 0            3.20
11798  geographically      1        RB                 0            5.60
11799      breakfasts      1     NN|VB                 0            4.30
11800        maturity      1        NN                 0            3.35

[11801 rows x 5 columns]

In [42]:
CSAT_only_POS_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_only_POS_N.xlsx'), index=False)
textbook_only_POS_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'textbook_only_POS_N.xlsx'), index=False)
CSAT_POS_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_POS_N.xlsx'), index=False)

In [55]:
CSAT_only_POS_df.columns= ['Word', 'CSAT_only_Freq', 'POS', 'Ortho_N_CSAT(only)', 'OLD20_CSAT(only)']
textbook_only_POS_df.columns= ['Word', 'Textbook_only_Freq', 'POS', 'Ortho_N_Textbook(only)', 'OLD20_Textbook(only)']
CSAT_POS_df.columns= ['Word', 'CSAT_Freq', 'POS', 'Ortho_N_CSAT', 'OLD20_CSAT']

In [68]:
CSAT_df = pd.merge(pd.merge(CSAT_only_POS_df.drop(columns=['POS']), textbook_only_POS_df, on='Word', how='outer').drop(columns=['POS']), CSAT_POS_df, on='Word', how='outer')
CSAT_df

,Word,CSAT_only_Freq,Ortho_N_CSAT(only),OLD20_CSAT(only),Textbook_only_Freq,Ortho_N_Textbook(only),OLD20_Textbook(only),CSAT_Freq,POS,Ortho_N_CSAT,OLD20_CSAT
0,a,9773.0,1.0,1.45,7732.0,1.0,1.45,17505,minor|NN,1,1.45
1,aaron,1.0,1.0,1.95,6.0,0.0,2.00,7,NN,1,1.85
2,abandon,5.0,0.0,3.05,2.0,0.0,3.00,7,VB|NN,0,2.90
3,abandoned,5.0,0.0,3.50,7.0,0.0,3.60,12,VB|JJ,0,3.50
4,abandoning,3.0,0.0,3.60,NaN,NaN,NaN,3,VB,0,3.60
...,...,...,...,...,...,...,...,...,...,...,...
16349,zombies,NaN,NaN,NaN,3.0,0.0,2.65,3,NN,0,2.60
16350,zone,6.0,7.0,1.40,13.0,7.0,1.40,19,NN,7,1.40
16351,zones,8.0,4.0,1.60,9.0,4.0,1.60,17,NN,4,1.60
16352,zoo,21.0,1.0,1.85,10.0,4.0,1.70,31,NN,4,1.70
16353,zoologist,2.0,0.0,3.90,NaN,NaN,NaN,2,NN,0,3.90

In [69]:
CSAT_df['Length'] = CSAT_df['Word'].apply(lambda x: len(x))
relative_unit = 1000000
CSAT_df['CSAT_RFreq'] = CSAT_df['CSAT_Freq'] / relative_unit
CSAT_df['CSAT_only_RFreq'] = CSAT_df['CSAT_only_Freq'] / relative_unit
CSAT_df['Textbook_only_RFreq'] = CSAT_df['Textbook_only_Freq'] / relative_unit

In [70]:
CSAT_df.columns, len(CSAT_df.columns)

(Index(['Word', 'CSAT_only_Freq', 'Ortho_N_CSAT(only)', 'OLD20_CSAT(only)',
        'Textbook_only_Freq', 'Ortho_N_Textbook(only)', 'OLD20_Textbook(only)',
        'CSAT_Freq', 'POS', 'Ortho_N_CSAT', 'OLD20_CSAT', 'Length',
        'CSAT_RFreq', 'CSAT_only_RFreq', 'Textbook_only_RFreq'],
       dtype='object'),
 15)

In [71]:
CSAT_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16354 entries, 0 to 16353
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Word                    16354 non-null  object
 1   CSAT_only_Freq          14009 non-null  float64
 2   Ortho_N_CSAT(only)      14009 non-null  float64
 3   OLD20_CSAT(only)        14009 non-null  float64
 4   Textbook_only_Freq      11801 non-null  float64
 5   Ortho_N_Textbook(only)  11801 non-null  float64
 6   OLD20_Textbook(only)    11801 non-null  float64
 7   CSAT_Freq               16354 non-null  int64
 8   POS                     16354 non-null  object
 9   Ortho_N_CSAT            16354 non-null  int64
 10  OLD20_CSAT              16354 non-null  float64
 11  Length                  16354 non-null  int64
 12  CSAT_RFreq              16354 non-null  float64
 13  CSAT_only_RFreq         14009 non-null  float64
 14  Textbook_only_RFreq     11801 non-null  float64
dtypes: float64(10), int64(3), object(2)
memory usage: 1.9+ MB

In [72]:
CSAT_df = CSAT_df[['Word', 'Length', 
                   'CSAT_Freq', 'CSAT_only_Freq', 'Textbook_only_Freq', 'CSAT_RFreq', 'CSAT_only_RFreq', 'Textbook_only_RFreq', 
                   'Ortho_N_CSAT', 'Ortho_N_CSAT(only)', 'Ortho_N_Textbook(only)', 
                   'OLD20_CSAT', 'OLD20_CSAT(only)', 'OLD20_Textbook(only)', 
                   'POS']]
CSAT_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_final.xlsx'), index=False)
CSAT_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16354 entries, 0 to 16353
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Word                    16354 non-null  object
 1   Length                  16354 non-null  int64
 2   CSAT_Freq               16354 non-null  int64
 3   CSAT_only_Freq          14009 non-null  float64
 4   Textbook_only_Freq      11801 non-null  float64
 5   CSAT_RFreq              16354 non-null  float64
 6   CSAT_only_RFreq         14009 non-null  float64
 7   Textbook_only_RFreq     11801 non-null  float64
 8   Ortho_N_CSAT            16354 non-null  int64
 9   Ortho_N_CSAT(only)      14009 non-null  float64
 10  Ortho_N_Textbook(only)  11801 non-null  float64
 11  OLD20_CSAT              16354 non-null  float64
 12  OLD20_CSAT(only)        14009 non-null  float64
 13  OLD20_Textbook(only)    11801 non-null  float64
 14  POS                     16354 non-null  object
dtypes: float64(10), int64(3), object(2)
memory usage: 1.9+ MB

## CSAT + E-lexicon-proj

## latest update

In [15]:
CSAT_df_path = os.path.join(corpora_dir, 'merged_corpora', 'CSAT_final.xlsx')
CSAT_df = pd.read_excel(CSAT_df_path)
CSAT_df

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,CSAT_RFreq,CSAT_only_RFreq,Textbook_only_RFreq,Ortho_N_CSAT,Ortho_N_CSAT(only),Ortho_N_Textbook(only),OLD20_CSAT,OLD20_CSAT(only),OLD20_Textbook(only),POS
0,a,1,17505,9773.0,7732.0,0.017505,0.009773,0.007732,1,1.0,1.0,1.45,1.45,1.45,minor|NN
1,aaron,5,7,1.0,6.0,0.000007,0.000001,0.000006,1,1.0,0.0,1.85,1.95,2.00,NN
2,abandon,7,7,5.0,2.0,0.000007,0.000005,0.000002,0,0.0,0.0,2.90,3.05,3.00,VB|NN
3,abandoned,9,12,5.0,7.0,0.000012,0.000005,0.000007,0,0.0,0.0,3.50,3.50,3.60,VB|JJ
4,abandoning,10,3,3.0,NaN,0.000003,0.000003,NaN,0,0.0,NaN,3.60,3.60,NaN,VB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16349,zombies,7,3,NaN,3.0,0.000003,NaN,0.000003,0,NaN,0.0,2.60,NaN,2.65,NN
16350,zone,4,19,6.0,13.0,0.000019,0.000006,0.000013,7,7.0,7.0,1.40,1.40,1.40,NN
16351,zones,5,17,8.0,9.0,0.000017,0.000008,0.000009,4,4.0,4.0,1.60,1.60,1.60,NN
16352,zoo,3,31,21.0,10.0,0.000031,0.000021,0.000010,4,1.0,4.0,1.70,1.85,1.70,NN
16353,zoologist,9,2,2.0,NaN,0.000002,0.000002,NaN,0,0.0,NaN,3.90,3.90,NaN,NN

In [42]:
E_lexicon_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'E_lexicon_preprocessed.xlsx'))
E_lexicon_df

,Word,Length,Freq_KF,Freq_HAL,SUBTLWF,SUBTLCD,Ortho_N,Freq_N,OLD,Concreteness_Rating,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,POS,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD
0,a,1,23237.0,10610626,20415.27,99.93,1,15.8,1.45,1.46,...,NaN,NaN,NaN,minor|NN,798.917,-0.013,333.849,662.087,-0.323,174.691
1,aah,3,1.0,222,52.71,7.56,2,7.4,1.85,NaN,...,NaN,NaN,NaN,NaN,816.429,0.214,186.029,646.400,-0.349,130.445
2,aaron,5,7.0,10806,14.65,1.93,3,7.4,1.85,NaN,...,NaN,NaN,NaN,NN,736.062,-0.111,289.010,686.111,-0.203,179.290
3,aback,5,2.0,387,0.29,0.18,0,NaN,1.95,1.65,...,NaN,NaN,NaN,RB,796.267,0.110,171.607,596.538,-0.550,89.453
4,abacus,6,NaN,513,0.24,0.12,0,NaN,2.90,4.52,...,NaN,NaN,NaN,NN,964.400,0.655,488.996,792.688,0.309,200.186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zoom,4,NaN,4920,3.55,1.29,4,9.2,1.70,3.10,...,5.86,5.68,5.90,VB|NN,549.758,-0.762,97.649,639.857,-0.441,108.340
40477,zooming,7,1.0,523,0.63,0.31,3,5.8,1.85,NaN,...,NaN,NaN,NaN,VB,709.690,-0.293,283.106,672.370,-0.218,92.353
40478,zooms,5,1.0,385,0.06,0.04,3,6.7,1.80,NaN,...,NaN,NaN,NaN,VB,666.933,-0.476,232.109,613.833,-0.552,88.295
40479,zucchini,8,NaN,314,0.96,0.25,0,NaN,3.75,4.87,...,6.30,4.18,6.19,NN,848.679,0.239,259.819,756.000,0.207,209.064
40480,zurich,6,2.0,1770,2.43,0.74,0,NaN,2.80,NaN,...,NaN,NaN,NaN,NN,763.000,0.091,184.257,822.640,0.213,221.482

In [43]:
E_lexicon_df.rename(columns={'SUBTLWF': 'SUBTLRWF'}, inplace=True)

HAL 코퍼스의 정확한 크기는 약 1억 3천1백만 단어에서 1억 6천만 단어 사이(SUBTLEX 논문에서도 오타가 있고, HAL을 소개하는 논문들 간에도 수치가 약간씩 다름.) 일단 130M으로 계산.

In [45]:
E_lexicon_df['SUBTLWF'] = E_lexicon_df['SUBTLRWF'] * 51
E_lexicon_df['RFreq_HAL'] = E_lexicon_df['Freq_HAL'] / 130
E_lexicon_df['RFreq_KF'] = E_lexicon_df['Freq_KF'] / 1.014

In [46]:
# Freq_N drop(1), 겹치는 col(Word, Length, POS) 3개 // 총 4개 컬럼 제거(36-4=32)
CSAT_df.columns, E_lexicon_df.columns, len(CSAT_df.columns), len(E_lexicon_df.columns)

(Index(['Word', 'Length', 'CSAT_Freq', 'CSAT_only_Freq', 'Textbook_only_Freq',
        'CSAT_RFreq', 'CSAT_only_RFreq', 'Textbook_only_RFreq', 'Ortho_N_CSAT',
        'Ortho_N_CSAT(only)', 'Ortho_N_Textbook(only)', 'OLD20_CSAT',
        'OLD20_CSAT(only)', 'OLD20_Textbook(only)', 'POS'],
       dtype='object'),
 Index(['Word', 'Length', 'Freq_KF', 'Freq_HAL', 'SUBTLRWF', 'SUBTLCD',
        'Ortho_N', 'Freq_N', 'OLD', 'Concreteness_Rating', 'Age_Of_Acquisition',
        'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance', 'POS',
        'I_Mean_RT', 'I_Zscore', 'I_SD', 'I_NMG_Mean_RT', 'I_NMG_Zscore',
        'I_NMG_SD', 'SUBTLWF', 'RFreq_HAL', 'RFreq_KF'],
       dtype='object'),
 15,
 24)

In [47]:
reodered_col = ['Word', 'Length', 
                           'CSAT_Freq', 'CSAT_only_Freq', 'Textbook_only_Freq', 'Freq_HAL', 'SUBTLWF', 'Freq_KF',
                           'CSAT_RFreq', 'CSAT_only_RFreq', 'Textbook_only_RFreq', 'RFreq_HAL', 'SUBTLRWF', 'RFreq_KF',
                           'Ortho_N_CSAT', 'Ortho_N_CSAT(only)', 'Ortho_N_Textbook(only)', 'Ortho_N',
                           'OLD20_CSAT', 'OLD20_CSAT(only)', 'OLD20_Textbook(only)', 'OLD',
                           'SUBTLCD', 'Concreteness_Rating', 'Age_Of_Acquisition', 'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance', 'I_Mean_RT', 'I_Zscore', 'I_SD', 'I_NMG_Mean_RT', 'I_NMG_Zscore', 'I_NMG_SD',
                           'POS']
len(reodered_col)

35

In [48]:
# 주의할 것. 
# 단어 중에 NaN이라는 단어가 있어서 이를 처리하다가보면 nan값으로 처리해버려서 excel에서 안 읽힘. 수작업으로 수정해야 됨.
CSAT_E_final_df = pd.merge(CSAT_df.drop(columns=['Length', 'POS']), E_lexicon_df, on='Word', how='outer')

CSAT_E_final_df =  CSAT_E_final_df[reodered_col]
CSAT_E_final_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_E_final.xlsx'), index=False)
CSAT_E_final_df

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Freq_HAL,SUBTLWF,Freq_KF,CSAT_RFreq,CSAT_only_RFreq,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,POS
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,0.017505,0.009773,...,NaN,NaN,NaN,798.917,-0.013,333.849,662.087,-0.323,174.691,minor|NN
1,aah,3,NaN,NaN,NaN,222,2688.21,1.0,NaN,NaN,...,NaN,NaN,NaN,816.429,0.214,186.029,646.400,-0.349,130.445,NaN
2,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,0.000007,0.000001,...,NaN,NaN,NaN,736.062,-0.111,289.010,686.111,-0.203,179.290,NN
3,aback,5,NaN,NaN,NaN,387,14.79,2.0,NaN,NaN,...,NaN,NaN,NaN,796.267,0.110,171.607,596.538,-0.550,89.453,RB
4,abacus,6,NaN,NaN,NaN,513,12.24,NaN,NaN,NaN,...,NaN,NaN,NaN,964.400,0.655,488.996,792.688,0.309,200.186,NN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zooming,7,NaN,NaN,NaN,523,32.13,1.0,NaN,NaN,...,NaN,NaN,NaN,709.690,-0.293,283.106,672.370,-0.218,92.353,VB
40477,zooms,5,NaN,NaN,NaN,385,3.06,1.0,NaN,NaN,...,NaN,NaN,NaN,666.933,-0.476,232.109,613.833,-0.552,88.295,VB
40478,zucchini,8,NaN,NaN,NaN,314,48.96,NaN,NaN,NaN,...,6.3,4.18,6.19,848.679,0.239,259.819,756.000,0.207,209.064,NN
40479,zurich,6,NaN,NaN,NaN,1770,123.93,2.0,NaN,NaN,...,NaN,NaN,NaN,763.000,0.091,184.257,822.640,0.213,221.482,NN
40480,NaN,4,NaN,NaN,NaN,15410,27.03,13.0,NaN,NaN,...,NaN,NaN,NaN,703.467,-0.278,168.922,595.741,-0.562,86.852,NN|JJ