# Corpus Merging.

## CSAT 만들기

CSAT의 경우, 자체적인 POS 값들 달기 애매하기 때문에 E-lexicon proj에서 제공하는 POS 값을 우선적으로 가져와서 붙여 넣자. 아마 대부분 있지 않을까?

### Module Import

In [1]:
import pandas as pd # 데이터 처리
import numpy as np # 데이터 처리
import seaborn as sns # 데이터 시각화
from tqdm import tqdm # 데이터 처리
import re # 정규식으로 특수기호 및 char 처리
import json # 데이터 가공 후 저장할 형식
from typing import Any, Dict, List  # python data-type 정의
from pathlib import Path # 파일 경로 처리
import os # 파일 경로 및 처리
from json_handler import JsonFileHandler
from preprocessor import Preprocessor, TargetCorpusPreprocessor

### file path setting

In [2]:
# 파일 경로 확인.
proj_path = os.path.dirname(os.path.dirname(Path.cwd()))
corpora_dir = os.path.join(proj_path, 'Corpora')
CSAT_json_path = save_path = os.path.join(corpora_dir, 'CSAT-latest')

# 파일 경로 유효성 확인.
if not os.path.exists(proj_path):
    raise FileNotFoundError(f"Project path not found at {proj_path}")
if not os.path.exists(CSAT_json_path):
    raise FileNotFoundError(f"CSAT json path not found at {CSAT_json_path}")
if not any(file.endswith('.json') for file in os.listdir(CSAT_json_path)):
    raise FileExistsError(f"Any .json file doesn't exist in {CSAT_json_path}")
print("All file paths are valid.")

All file paths are valid.

### Utils: generate_word_list
중복을 허용하여 단어를 extend 한 list 생성.
이후 pandas 다른 method(ex: value_count)를 사용해서 빈도수 계산.

In [17]:
def generate_word_list(document_list: list, document_dir: str):
    # article 별 단어 분석.
    word_list = []   # word 정보를 담을 리스트
    json_handler = JsonFileHandler()

    for document_name in document_list: # corpus에서 하나의 json 파일을 가져와서
        document = json_handler.load_data(os.path.join(document_dir, document_name))  # 하나의 json 파일 내에 있는 모든 파일을 가져옴.

        if isinstance(document, list):   # 한 json 내에 여러 obj가 있는 경우, 
            for sentence in document:  # json 파일 내 있는 여러 문장들 수 
                word_list.extend(sentence['tokens'])
        else:   # 한 json 내에 하나의 obj가 있는 경우, 
            word_list.extend(document['tokens'])   

    return word_list

### CSAT(only): 수능 + 모의고사

In [5]:
json_handler = JsonFileHandler()
CSAT_path = os.path.join(corpora_dir, 'CSAT-latest')
corpus_list = os.listdir(CSAT_path)
corpus_list = [file for file in corpus_list if file.endswith('.json')]
reading_corpus = [file for file in corpus_list if 'reading' in file]
listening_corpus = [file for file in corpus_list if 'listening' in file]

len(reading_corpus), len(listening_corpus)

(52, 49)

In [7]:
listening_word_list = generate_word_list(listening_corpus, CSAT_path)
reading_word_list = generate_word_list(reading_corpus, CSAT_path)
CSAT_only_word_list = pd.Series(listening_word_list + reading_word_list)

In [8]:
CSAT_only_word_list.shape

(482265,)

In [9]:
CSAT_only_word_list.value_counts()

.            32877
,            21944
the          21540
to           12665
of           10010
             ...
arabian          1
sapphire         1
sandstone        1
khyber           1
doubly           1
Name: count, Length: 17438, dtype: int64

In [10]:
CSAT_only_word_list_df = CSAT_only_word_list.value_counts().to_frame().reset_index().rename(columns={'index': 'Word', 'count': 'Freq'})
CSAT_only_word_list_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_only.xlsx'), index=False)
CSAT_only_word_list_df

            Word   Freq
0              .  32877
1              ,  21944
2            the  21540
3             to  12665
4             of  10010
...          ...    ...
17433    arabian      1
17434   sapphire      1
17435  sandstone      1
17436     khyber      1
17437     doubly      1

[17438 rows x 2 columns]

### textbook(only)

In [11]:
json_handler = JsonFileHandler()
CSAT_path = os.path.join(corpora_dir, 'CSAT-latest')
corpus_list = os.listdir(CSAT_path)
corpus_list = [file for file in corpus_list if file.endswith('.json')]
textbook_corpus = [file for file in corpus_list if 'textbook' in file]

len(textbook_corpus)

71

In [12]:
textbook_word_list = generate_word_list(textbook_corpus, CSAT_path)
textbook_only_word_list = pd.Series(textbook_word_list)

In [13]:
textbook_only_word_list.shape

(352760,)

In [14]:
textbook_only_word_list.value_counts()

.                 22088
the               16763
,                 16722
to                 9000
and                7844
                  ...
elegance              1
geographically        1
breakfasts            1
whiteboard            1
maturity              1
Name: count, Length: 14822, dtype: int64

In [15]:
textbook_only_word_list_df = textbook_only_word_list.value_counts().to_frame().reset_index().rename(columns={'index': 'Word', 'count': 'Freq'})
textbook_only_word_list_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'textbook_only.xlsx'), index=False)
textbook_only_word_list_df

                 Word   Freq
0                   .  22088
1                 the  16763
2                   ,  16722
3                  to   9000
4                 and   7844
...               ...    ...
14817        elegance      1
14818  geographically      1
14819      breakfasts      1
14820      whiteboard      1
14821        maturity      1

[14822 rows x 2 columns]

### CSAT Total

In [4]:
json_handler = JsonFileHandler()
CSAT_path = os.path.join(corpora_dir, 'CSAT-latest')
corpus_list = os.listdir(CSAT_path)
corpus_list = [file for file in corpus_list if file.endswith('.json')]
reading_corpus = [file for file in corpus_list if 'reading' in file]
listening_corpus = [file for file in corpus_list if 'listening' in file]
textbook_corpus = [file for file in corpus_list if 'textbook' in file]

len(reading_corpus), len(listening_corpus), len(textbook_corpus)

(52, 49, 71)

In [7]:
listening_word_list = generate_word_list(listening_corpus, CSAT_path)
reading_word_list = generate_word_list(reading_corpus, CSAT_path)
textbook_word_list = generate_word_list(textbook_corpus, CSAT_path)
CSAT_word_list = pd.Series(listening_word_list + reading_word_list + textbook_word_list)

In [8]:
CSAT_word_list.shape

(835025,)

In [9]:
CSAT_word_list.value_counts()

.             54965
,             38666
the           38303
to            21665
a             17505
              ...
tersely           1
trimly            1
imbricate         1
sepals            1
regretting        1
Name: count, Length: 22147, dtype: int64

In [10]:
CSAT_word_list_df = CSAT_word_list.value_counts().to_frame().reset_index().rename(columns={'index': 'Word', 'count': 'Freq'})
#CSAT_word_list_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT.xlsx'), index=False)
CSAT_word_list_df

             Word   Freq
0               .  54965
1               ,  38666
2             the  38303
3              to  21665
4               a  17505
...           ...    ...
22142     tersely      1
22143      trimly      1
22144   imbricate      1
22145      sepals      1
22146  regretting      1

[22147 rows x 2 columns]

In [ ]:
# spell checker를 사용해서, 오타가 있는 단어를 찾아보자.
CSAT = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT.xlsx'))
from spellchecker import SpellChecker
from tqdm import tqdm
spell = SpellChecker()

isWord = []

for word in tqdm(CSAT['Word']):
    if word != spell.correction(word):
        isWord.append(False)
    else:
        isWord.append(True)
CSAT['isWord'] = isWord
CSAT

100%|██████████| 22147/22147 [07:06<00:00, 51.87it/s]

             Word   Freq  isWord
0               .  54965    True
1               ,  38666    True
2             the  38303    True
3              to  21665    True
4               a  17505    True
...           ...    ...     ...
22142     tersely      1    True
22143      trimly      1    True
22144   imbricate      1    True
22145      sepals      1    True
22146  regretting      1    True

[22147 rows x 3 columns]

잘 구분 되지 않는 것 같기도 하고, 이상한 건 보통 빈도가 낮은 것 같아 보여, 건드리지 않고, 다만, 최상위 2개 comma, dot 은 빈도수가 높아 제외.

In [25]:
CSAT.reset_index(drop=True, inplace=True)
CSAT.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT.xlsx'), index=False)

In [28]:
CSAT[CSAT['isWord'] == False]

               Word  Freq  isWord
82               ll  1100   False
194              ve   435   False
238            didn   345   False
505           doesn   170   False
597             isn   144   False
...             ...   ...     ...
22104       plesant     1   False
22105        'pause     1   False
22106      akampani     1   False
22108      ordinaiy     1   False
22113  onesidedness     1   False

[2435 rows x 3 columns]

## E-lexicon proj

E-lexicon proj를 보면, a의 orthographic N이 1이다. 즉, b,c,d,e 같이 치환된 케이스 중 비단어는 제외했다는 말이니, CSAT도 그대로 사용하기는 무리. 따라서 E-lexicon이랑 intersection을 먼저 시켜봐야 할 듯.

In [32]:
E_lexicon_proj_path = os.path.join(corpora_dir, 'E-lexicon-proj')

In [33]:
E_lexicon_df = pd.read_csv(os.path.join(E_lexicon_proj_path, 'English Lexicon Project Items.csv'))
E_lexicon_df.head()

,Word,Length,Freq_KF,Freq_HAL,SUBTLWF,SUBTLCD,Ortho_N,Phono_N,OLD,PLD,...,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,I_NMG_Obs,I_NMG_Mean_Accuracy
0,a,1,"23,237","10,610,626","20,415.270",99.930,1,8,1.450,1.000,...,798.917,-0.013,333.849,24,0.73,662.087,-0.323,174.691,23,0.958
1,aah,3,1,222,52.710,7.560,2,0,1.850,3.000,...,816.429,0.214,186.029,21,0.62,646.400,-0.349,130.445,25,0.926
2,Aaron,5,7,"10,806",14.650,1.930,3,2,1.850,1.600,...,736.062,-0.111,289.010,32,0.97,686.111,-0.203,179.290,27,1.000
3,aback,5,2,387,0.290,0.180,0,2,1.950,1.850,...,796.267,0.110,171.607,15,0.45,596.538,-0.550,89.453,26,0.963
4,abacus,6,#,513,0.240,0.120,0,0,2.900,2.900,...,964.400,0.655,488.996,15,0.47,792.688,0.309,200.186,16,0.615

In [34]:
# null이라는 단어가 있는데, type 지정을 안 해주면 null 값으로 분류됨.
E_lexicon_df['Word'] = E_lexicon_df['Word'].astype(str)
E_lexicon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Word                           40481 non-null  object
 1   Length                         40481 non-null  int64
 2   Freq_KF                        40481 non-null  object
 3   Freq_HAL                       40481 non-null  object
 4   SUBTLWF                        40481 non-null  object
 5   SUBTLCD                        40481 non-null  object
 6   Ortho_N                        40481 non-null  int64
 7   Phono_N                        40481 non-null  int64
 8   OLD                            40481 non-null  object
 9   PLD                            40481 non-null  object
 10  Concreteness_Rating            40481 non-null  object
 11  Semantic_Neighborhood_Density  40481 non-null  object
 12  Semantic_Neighbors             40481 non-null  object
 13  Semantic_Diversity             40481 non-null  object
 14  Age_Of_Acquisition             40481 non-null  object
 15  Body_Object_Interaction        40481 non-null  object
 16  Emotional_Valence              40481 non-null  object
 17  Emotional_Arousal              40481 non-null  object
 18  Emotional_Dominance            40481 non-null  object
 19  Assoc_Freq_R1                  40481 non-null  object
 20  Assoc_Types_R1                 40481 non-null  object
 21  Assoc_Freq_R123                40481 non-null  object
 22  Assoc_Types_R123               40481 non-null  object
 23  POS                            40481 non-null  object
 24  I_Mean_RT                      40481 non-null  object
 25  I_Zscore                       40481 non-null  object
 26  I_SD                           40481 non-null  object
 27  Obs                            40481 non-null  object
 28  I_Mean_Accuracy                40481 non-null  float64
 29  I_NMG_Mean_RT                  40481 non-null  object
 30  I_NMG_Zscore                   40481 non-null  float64
 31  I_NMG_SD                       40481 non-null  object
 32  I_NMG_Obs                      40481 non-null  int64
 33  I_NMG_Mean_Accuracy            40481 non-null  float64
dtypes: float64(3), int64(4), object(27)
memory usage: 10.5+ MB

E-lexicon proj에서도 Word는 lower 적용.

In [35]:
E_lexicon_df['Word'] = E_lexicon_df['Word'].str.lower()
E_lexicon_df.head()

,Word,Length,Freq_KF,Freq_HAL,SUBTLWF,SUBTLCD,Ortho_N,Phono_N,OLD,PLD,...,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,I_NMG_Obs,I_NMG_Mean_Accuracy
0,a,1,"23,237","10,610,626","20,415.270",99.930,1,8,1.450,1.000,...,798.917,-0.013,333.849,24,0.73,662.087,-0.323,174.691,23,0.958
1,aah,3,1,222,52.710,7.560,2,0,1.850,3.000,...,816.429,0.214,186.029,21,0.62,646.400,-0.349,130.445,25,0.926
2,aaron,5,7,"10,806",14.650,1.930,3,2,1.850,1.600,...,736.062,-0.111,289.010,32,0.97,686.111,-0.203,179.290,27,1.000
3,aback,5,2,387,0.290,0.180,0,2,1.950,1.850,...,796.267,0.110,171.607,15,0.45,596.538,-0.550,89.453,26,0.963
4,abacus,6,#,513,0.240,0.120,0,0,2.900,2.900,...,964.400,0.655,488.996,15,0.47,792.688,0.309,200.186,16,0.615

In [ ]:
from preprocessor import TargetCorpusPreprocessor

E_lexicon_df = TargetCorpusPreprocessor(E_lexicon_df).preprocess()
E_lexicon_df['Word'] = E_lexicon_df['Word'].astype(str)
E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'E_lexicon_preprocessed.xlsx'), index=False)

Cleaning information col by col:   0%|          | 0/34 [00:00<?, ?it/s]

Freq_KF

Cleaning information col by col:   9%|▉         | 3/34 [00:03<00:33,  1.07s/it]

Freq_HAL
SUBTLWF

Cleaning information col by col:  15%|█▍        | 5/34 [00:04<00:27,  1.04it/s]

SUBTLCD

Cleaning information col by col:  18%|█▊        | 6/34 [00:06<00:31,  1.13s/it]

OLD

Cleaning information col by col:  26%|██▋       | 9/34 [00:06<00:14,  1.69it/s]

PLD

Cleaning information col by col:  29%|██▉       | 10/34 [00:07<00:13,  1.84it/s]

Concreteness_Rating

Cleaning information col by col:  32%|███▏      | 11/34 [00:14<00:46,  2.03s/it]

Semantic_Neighborhood_Density

Cleaning information col by col:  35%|███▌      | 12/34 [00:14<00:35,  1.63s/it]

Semantic_Neighbors

Cleaning information col by col:  38%|███▊      | 13/34 [00:15<00:28,  1.36s/it]

Semantic_Diversity

Cleaning information col by col:  41%|████      | 14/34 [00:21<00:52,  2.63s/it]

Age_Of_Acquisition

Cleaning information col by col:  44%|████▍     | 15/34 [00:24<00:54,  2.86s/it]

Body_Object_Interaction

Cleaning information col by col:  47%|████▋     | 16/34 [00:42<02:04,  6.93s/it]

Emotional_Valence

Cleaning information col by col:  50%|█████     | 17/34 [00:56<02:33,  9.03s/it]

Emotional_Arousal

Cleaning information col by col:  53%|█████▎    | 18/34 [01:10<02:50, 10.63s/it]

Emotional_Dominance

Cleaning information col by col:  56%|█████▌    | 19/34 [01:25<02:57, 11.82s/it]

Assoc_Freq_R1

Cleaning information col by col:  59%|█████▉    | 20/34 [01:32<02:25, 10.40s/it]

Assoc_Types_R1

Cleaning information col by col:  62%|██████▏   | 21/34 [01:39<02:02,  9.40s/it]

Assoc_Freq_R123

Cleaning information col by col:  65%|██████▍   | 22/34 [01:43<01:33,  7.81s/it]

Assoc_Types_R123

Cleaning information col by col: 100%|██████████| 34/34 [01:48<00:00,  3.18s/it]

POS
I_Mean_RT
I_Zscore
I_SD
Obs
I_NMG_Mean_RT
I_NMG_SD

In [42]:
E_lexicon_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'E_lexicon_preprocessed.xlsx'))
E_lexicon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Word                           40480 non-null  object
 1   Length                         40481 non-null  int64
 2   Freq_KF                        32552 non-null  float64
 3   Freq_HAL                       40481 non-null  int64
 4   SUBTLWF                        35515 non-null  float64
 5   SUBTLCD                        35515 non-null  float64
 6   Ortho_N                        40481 non-null  int64
 7   Phono_N                        40481 non-null  int64
 8   OLD                            39382 non-null  float64
 9   PLD                            39382 non-null  float64
 10  Concreteness_Rating            23562 non-null  float64
 11  Semantic_Neighborhood_Density  39241 non-null  float64
 12  Semantic_Neighbors             39241 non-null  float64
 13  Semantic_Diversity             25858 non-null  float64
 14  Age_Of_Acquisition             31440 non-null  float64
 15  Body_Object_Interaction        8984 non-null   float64
 16  Emotional_Valence              12742 non-null  float64
 17  Emotional_Arousal              12742 non-null  float64
 18  Emotional_Dominance            12742 non-null  float64
 19  Assoc_Freq_R1                  24226 non-null  float64
 20  Assoc_Types_R1                 24226 non-null  float64
 21  Assoc_Freq_R123                29722 non-null  float64
 22  Assoc_Types_R123               29722 non-null  float64
 23  POS                            39903 non-null  object
 24  I_Mean_RT                      40468 non-null  float64
 25  I_Zscore                       40468 non-null  float64
 26  I_SD                           40450 non-null  float64
 27  Obs                            40468 non-null  float64
 28  I_Mean_Accuracy                40481 non-null  float64
 29  I_NMG_Mean_RT                  40481 non-null  float64
 30  I_NMG_Zscore                   40481 non-null  float64
 31  I_NMG_SD                       40477 non-null  float64
 32  I_NMG_Obs                      40481 non-null  int64
 33  I_NMG_Mean_Accuracy            40481 non-null  float64
dtypes: float64(27), int64(5), object(2)
memory usage: 10.5+ MB

### CSAT_edit

In [34]:
CSAT_only_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_only.xlsx'))
textbook_only_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'textbook_only.xlsx'))
CSAT_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT.xlsx'))

# overlap 1562개
CSAT_df.shape, CSAT_only_df.shape,textbook_only_df.shape

((22147, 2), (17438, 2), (14822, 2))

각각 E-lexicon이랑 합치고 POS 달기

In [35]:
CSAT_only_POS_df = pd.merge(CSAT_only_df, E_lexicon_df, on='Word', how='inner')[['Word', 'Freq', 'POS']]
CSAT_only_POS_df = CSAT_only_POS_df.dropna(subset=['POS']).reset_index(drop=True)
CSAT_only_POS_df

            Word   Freq       POS
0            the  21540     minor
1             to  12665     minor
2             of  10010     minor
3              a   9773  minor|NN
4            and   8974     minor
...          ...    ...       ...
14004   fortress      1        NN
14005    arabian      1     NN|JJ
14006   sapphire      1        NN
14007  sandstone      1        NN
14008     doubly      1        RB

[14009 rows x 3 columns]

In [36]:
textbook_only_POS_df = pd.merge(textbook_only_df, E_lexicon_df, on='Word', how='inner')[['Word', 'Freq', 'POS']]
textbook_only_POS_df = textbook_only_POS_df.dropna(subset=['POS']).reset_index(drop=True)
textbook_only_POS_df

                 Word   Freq       POS
0                 the  16763     minor
1                  to   9000     minor
2                 and   7844     minor
3                   a   7732  minor|NN
4                  of   7161     minor
...               ...    ...       ...
11796        deathbed      1        NN
11797        elegance      1        NN
11798  geographically      1        RB
11799      breakfasts      1     NN|VB
11800        maturity      1        NN

[11801 rows x 3 columns]

In [37]:
CSAT_POS_df = pd.merge(CSAT_df, E_lexicon_df, on='Word', how='inner')[['Word', 'Freq', 'POS']]
CSAT_POS_df = CSAT_POS_df.dropna(subset=['POS']).reset_index(drop=True)
CSAT_POS_df

            Word   Freq       POS
0            the  38303     minor
1             to  21665     minor
2              a  17505  minor|NN
3             of  17171     minor
4            and  16818     minor
...          ...    ...       ...
16349      vomit      1     VB|NN
16350  surpluses      1        NN
16351   resented      1     VB|JJ
16352     winded      1     JJ|VB
16353    tersely      1        RB

[16354 rows x 3 columns]

### 그렇다면 차집합도 볼만 하겠지?

In [116]:
CSAT = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT.xlsx'))
CSAT

             Word   Freq  isWord
0               .  54965    True
1               ,  38666    True
2             the  38303    True
3              to  21665    True
4               a  17505    True
...           ...    ...     ...
22142     tersely      1    True
22143      trimly      1    True
22144   imbricate      1    True
22145      sepals      1    True
22146  regretting      1    True

[22147 rows x 3 columns]

In [117]:
E_lexicon_df

,Word,Length,Freq_KF,Freq_HAL,Freq_SUBTLEX,SUBTLCD,Ortho_N,Phono_N,OLD,PLD,...,LDT_RT_MEAN,LDT_RT_ZSCORE,LDT_RT_SD,LDT_RT_OBS,LDT_ACC_MEAN,NMG_RT_MEAN,NMG_RT_ZSCORE,NMG_RT_SD,NMG_RT_OBS,NMG_ACC_MEAN
0,a,1,23237.0,10610626,20415.27,99.93,1,8,1.45,1.00,...,798.917,-0.013,333.849,24.0,0.73,662.087,-0.323,174.691,23,0.958
1,aah,3,1.0,222,52.71,7.56,2,0,1.85,3.00,...,816.429,0.214,186.029,21.0,0.62,646.400,-0.349,130.445,25,0.926
2,aaron,5,7.0,10806,14.65,1.93,3,2,1.85,1.60,...,736.062,-0.111,289.010,32.0,0.97,686.111,-0.203,179.290,27,1.000
3,aback,5,2.0,387,0.29,0.18,0,2,1.95,1.85,...,796.267,0.110,171.607,15.0,0.45,596.538,-0.550,89.453,26,0.963
4,abacus,6,NaN,513,0.24,0.12,0,0,2.90,2.90,...,964.400,0.655,488.996,15.0,0.47,792.688,0.309,200.186,16,0.615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zoom,4,NaN,4920,3.55,1.29,4,7,1.70,1.55,...,549.758,-0.762,97.649,33.0,1.00,639.857,-0.441,108.340,28,1.000
40477,zooming,7,1.0,523,0.63,0.31,3,3,1.85,1.85,...,709.690,-0.293,283.106,29.0,0.88,672.370,-0.218,92.353,27,1.000
40478,zooms,5,1.0,385,0.06,0.04,3,5,1.80,1.75,...,666.933,-0.476,232.109,30.0,0.94,613.833,-0.552,88.295,24,1.000
40479,zucchini,8,NaN,314,0.96,0.25,0,0,3.75,2.90,...,848.679,0.239,259.819,28.0,0.85,756.000,0.207,209.064,23,0.958
40480,zurich,6,2.0,1770,2.43,0.74,0,0,2.80,2.20,...,763.000,0.091,184.257,21.0,0.64,822.640,0.213,221.482,25,0.893

In [123]:
# KE에만 있는 단어고 E-lexicon에는 없는데 그럴만한가?
pd.merge(CSAT, E_lexicon_df, on='Word', how='outer', indicator=True)['_merge']

0         left_only
1         left_only
2         left_only
3         left_only
4         left_only
            ...
46250    right_only
46251     left_only
46252     left_only
46253     left_only
46254    right_only
Name: _merge, Length: 46255, dtype: category
Categories (3, object): ['left_only', 'right_only', 'both']

In [26]:
E_lexicon_df[E_lexicon_df['POS'].isna() == True]

,Word,Length,Freq_HAL,Log_Freq_HAL,SUBTLWF,LgSUBTLWF,SUBTLCD,LgSUBTLCD,Ortho_N,OLD,POS
1,aah,3,222,5.403,52.71,3.430,7.56,2.803,2,1.85,NaN
361,actor's,7,363,5.894,NaN,NaN,NaN,NaN,0,NaN,NaN
708,agamemnon's,11,16,2.773,NaN,NaN,NaN,NaN,0,NaN,NaN
812,airbladder,10,0,0.000,NaN,NaN,NaN,NaN,0,4.30,NaN
814,airbrake,8,22,3.091,NaN,NaN,NaN,NaN,0,3.45,NaN
...,...,...,...,...,...,...,...,...,...,...,...
40198,worshiped,9,331,5.802,0.43,1.362,0.26,1.362,0,3.30,NaN
40299,wyndham's,9,12,2.485,NaN,NaN,NaN,NaN,0,NaN,NaN
40310,yachters,8,2,0.693,NaN,NaN,NaN,NaN,0,2.95,NaN
40403,yorker's,8,16,2.773,NaN,NaN,NaN,NaN,1,NaN,NaN
40418,youngster's,11,41,3.714,NaN,NaN,NaN,NaN,0,NaN,NaN

In [27]:
CSAT_only_diff_E_lexicon_df = pd.merge(CSAT_only_df, E_lexicon_df, on='Word', how='outer', indicator=True)[['Word', 'Freq', 'POS', '_merge']]
#CSAT_only_minus_E_lexicon_df = CSAT_only_minus_E_lexicon_df.dropna(subset=['POS']).reset_index(drop=True)
CSAT_only_diff_E_lexicon_df = CSAT_only_diff_E_lexicon_df[CSAT_only_diff_E_lexicon_df['_merge'] != 'both'].reset_index(drop=True)
CSAT_only_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_only_diff_E_lexicon.xlsx'), index=False)
CSAT_only_diff_E_lexicon_df

           Word  Freq    POS      _merge
0             '  31.0    NaN   left_only
1            ''   1.0    NaN   left_only
2      'bambuco   1.0    NaN   left_only
3         'best   1.0    NaN   left_only
4       'cumbia   1.0    NaN   left_only
...         ...   ...    ...         ...
29868  zucchini   NaN     NN  right_only
29869  zukerman   3.0    NaN   left_only
29870     zulus   1.0    NaN   left_only
29871    zurich   NaN     NN  right_only
29872       NaN   NaN  NN|JJ  right_only

[29873 rows x 4 columns]

In [28]:
textbook_only_diff_E_lexicon_df = pd.merge(textbook_only_df, E_lexicon_df, on='Word', how='outer', indicator=True)[['Word', 'Freq', 'POS', '_merge']]
#CSAT_only_minus_E_lexicon_df = CSAT_only_minus_E_lexicon_df.dropna(subset=['POS']).reset_index(drop=True)
textbook_only_diff_E_lexicon_df = textbook_only_diff_E_lexicon_df[textbook_only_diff_E_lexicon_df['_merge'] != 'both'].reset_index(drop=True)
textbook_only_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'textbook_only_diff_E_lexicon.xlsx'), index=False)
textbook_only_diff_E_lexicon_df

           Word  Freq    POS      _merge
0             '   8.0    NaN   left_only
1            'd   2.0    NaN   left_only
2            'i   1.0    NaN   left_only
3           'll   1.0    NaN   left_only
4            't   1.0    NaN   left_only
...         ...   ...    ...         ...
31682     zquez   2.0    NaN   left_only
31683  zucchini   NaN     NN  right_only
31684      zulu   3.0    NaN   left_only
31685    zurich   NaN     NN  right_only
31686       NaN   NaN  NN|JJ  right_only

[31687 rows x 4 columns]

In [29]:
CSAT_diff_E_lexicon_df = pd.merge(CSAT_df, E_lexicon_df, on='Word', how='outer', indicator=True)[['Word', 'Freq', 'POS', '_merge']]
#CSAT_minus_E_lexicon_df = CSAT_minus_E_lexicon_df.dropna(subset=['POS']).reset_index(drop=True)
CSAT_diff_E_lexicon_df = CSAT_diff_E_lexicon_df[CSAT_diff_E_lexicon_df['_merge'] != 'both'].reset_index(drop=True)
CSAT_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_diff_E_lexicon.xlsx'), index=False)
CSAT_diff_E_lexicon_df

           Word  Freq    POS      _merge
0             '  39.0    NaN   left_only
1            ''   1.0    NaN   left_only
2      'bambuco   1.0    NaN   left_only
3         'best   1.0    NaN   left_only
4       'cumbia   1.0    NaN   left_only
...         ...   ...    ...         ...
29877  zukerman   3.0    NaN   left_only
29878      zulu   3.0    NaN   left_only
29879     zulus   1.0    NaN   left_only
29880    zurich   NaN     NN  right_only
29881       NaN   NaN  NN|JJ  right_only

[29882 rows x 4 columns]

In [30]:
CSAT_only_diff_E_lexicon_df = CSAT_only_diff_E_lexicon_df.drop(columns=['POS', '_merge'])
CSAT_only_diff_E_lexicon_df.columns = ['Word', 'CSAT_only_Freq']
CSAT_only_diff_E_lexicon_df

           Word  CSAT_only_Freq
0             '            31.0
1            ''             1.0
2      'bambuco             1.0
3         'best             1.0
4       'cumbia             1.0
...         ...             ...
29868  zucchini             NaN
29869  zukerman             3.0
29870     zulus             1.0
29871    zurich             NaN
29872       NaN             NaN

[29873 rows x 2 columns]

In [31]:
textbook_only_diff_E_lexicon_df = textbook_only_diff_E_lexicon_df.drop(columns=['POS', '_merge'])
textbook_only_diff_E_lexicon_df.columns = ['Word', 'textbook_only_Freq']
textbook_only_diff_E_lexicon_df

           Word  textbook_only_Freq
0             '                 8.0
1            'd                 2.0
2            'i                 1.0
3           'll                 1.0
4            't                 1.0
...         ...                 ...
31682     zquez                 2.0
31683  zucchini                 NaN
31684      zulu                 3.0
31685    zurich                 NaN
31686       NaN                 NaN

[31687 rows x 2 columns]

In [32]:
CSAT_diff_E_lexicon_df = CSAT_diff_E_lexicon_df.drop(columns=['POS'])
CSAT_diff_E_lexicon_df.columns = ['Word', 'CSAT_Freq', '_merge']
CSAT_diff_E_lexicon_df

           Word  CSAT_Freq      _merge
0             '       39.0   left_only
1            ''        1.0   left_only
2      'bambuco        1.0   left_only
3         'best        1.0   left_only
4       'cumbia        1.0   left_only
...         ...        ...         ...
29877  zukerman        3.0   left_only
29878      zulu        3.0   left_only
29879     zulus        1.0   left_only
29880    zurich        NaN  right_only
29881       NaN        NaN  right_only

[29882 rows x 3 columns]

In [33]:
CSAT_diff_E_lexicon_df = pd.merge(pd.merge(CSAT_only_diff_E_lexicon_df, textbook_only_diff_E_lexicon_df, on='Word', how='outer'), CSAT_diff_E_lexicon_df, on='Word', how='outer')
CSAT_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_diff_E_lexicon.xlsx'), index=False)
CSAT_diff_E_lexicon_df

           Word  CSAT_only_Freq  textbook_only_Freq  CSAT_Freq      _merge
0             '            31.0                 8.0       39.0   left_only
1            ''             1.0                 NaN        1.0   left_only
2      'bambuco             1.0                 NaN        1.0   left_only
3         'best             1.0                 NaN        1.0   left_only
4       'cumbia             1.0                 NaN        1.0   left_only
...         ...             ...                 ...        ...         ...
36792  zukerman             3.0                 NaN        3.0   left_only
36793      zulu             NaN                 3.0        3.0   left_only
36794     zulus             1.0                 NaN        1.0   left_only
36795    zurich             NaN                 NaN        NaN  right_only
36796       NaN             NaN                 NaN        NaN  right_only

[36797 rows x 5 columns]

In [12]:
import requests
from nltk.corpus import wordnet
import nltk
nltk.download('wordnet')

def check_word_exists(word):
    
    # 2. WordNet으로 확인
    if wordnet.synsets(word):
        return True
    
    
    # 3. Free Dictionary API로 확인
    try:
        print(f"Checking {word}...")
        response = requests.get(f"https://api.dictionaryapi.dev/api/v2/entries/en/{word}", timeout=5)
        if response.status_code == 200:
            return True
        else:
            return False
    except:
        return False

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [13]:
check_word_exists('zookeeper')

Checking zookeeper...

True

In [ ]:
is_exit_list = []
for i, item in tqdm(enumerate(CSAT_diff_E_lexicon_df['Word'])):
    if check_word_exists(item) == True:
        is_exit_list.append(True)
    else:
        is_exit_list.append(False)
CSAT_diff_E_lexicon_df['is_exist'] = is_exit_list

CSAT_diff_E_lexicon_df[CSAT_diff_E_lexicon_df['is_exist'] == False]

0it [00:00, ?it/s]

Checking '...

1it [00:25, 25.78s/it]

Checking ''...

2it [00:56, 28.49s/it]

Checking 'bambuco...

3it [01:26, 29.39s/it]

Checking 'best...

4it [01:57, 29.83s/it]

Checking 'cumbia...

5it [02:27, 30.02s/it]

Checking 'd...

6it [02:58, 30.35s/it]

Checking 'fragile...

7it [03:28, 30.37s/it]

Checking 'hand...

8it [03:59, 30.52s/it]

Checking 'i...

9it [04:30, 30.51s/it]

Checking 'laughmobile...

10it [05:00, 30.47s/it]

Checking 'leaking...

11it [05:31, 30.56s/it]

Checking 'll...

12it [06:02, 30.63s/it]

Checking 'm...

13it [06:32, 30.57s/it]

Checking 'maybe...

14it [07:02, 30.51s/it]

Checking 'pause...

15it [07:33, 30.47s/it]

Checking 're...

16it [08:03, 30.47s/it]

Checking 'rich...

17it [08:34, 30.46s/it]

Checking 't...

18it [09:04, 30.51s/it]

Checking 'truth...

19it [09:35, 30.58s/it]

Checking 've...

20it [10:06, 30.63s/it]

Checking 'why...

21it [10:37, 30.66s/it]

Checking 'wilderness...

22it [11:07, 30.72s/it]

Checking ,...

23it [11:38, 30.56s/it]

Checking ....

24it [12:08, 30.63s/it]

Checking abab...

27it [12:39, 19.16s/it]

Checking ababababababab...

28it [13:10, 21.61s/it]

Checking abdi...

47it [13:41,  4.59s/it]

Checking abdul...

53it [14:11,  4.73s/it]

Checking abe...

54it [14:42,  6.35s/it]

Checking abebe...

55it [15:13,  8.33s/it]

Checking abel's...

58it [15:43,  8.80s/it]

Checking abigail...

71it [16:14,  4.84s/it]

Checking ableshipping...

74it [16:45,  5.75s/it]

Checking abu...

152it [17:16,  1.13s/it]

Checking aburke...

155it [17:46,  1.55s/it]

Checking academi...

165it [18:17,  1.81s/it]

Checking accessors...

193it [18:47,  1.51s/it]

Checking accidently...

195it [19:18,  2.07s/it]

Checking achieveddraining...

254it [19:48,  1.09s/it]

Checking achoo...

258it [20:19,  1.47s/it]

Checking acidmost...

264it [20:49,  1.87s/it]

Checking activites...

308it [21:20,  1.24s/it]

Checking actor's...

309it [21:51,  1.75s/it]

Checking ada's...

322it [22:22,  1.90s/it]

Checking adaily...

325it [22:53,  2.52s/it]

Checking adam's...

326it [23:23,  3.46s/it]

Checking adaptively...

334it [23:54,  3.55s/it]

Checking addae...

336it [24:24,  4.63s/it]

Checking adele...

352it [24:55,  3.25s/it]

Checking adia...

367it [25:26,  2.76s/it]

Checking adirondack...

371it [25:56,  3.42s/it]

Checking adlai...

397it [26:27,  2.18s/it]

Checking admin...

398it [26:58,  3.03s/it]

Checking administration's...

403it [27:29,  3.58s/it]

Checking adolescent's...

430it [28:00,  2.18s/it]

Checking adolf...

432it [28:04,  2.16s/it]

Checking adrianna...

In [ ]:
CSAT_diff_E_lexicon_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_diff_E_lexicon.xlsx'), index=False)

add Ortho_N, OLD20

In [39]:
from neighborhood import orthographic_N, OLD20

lexicon = CSAT_POS_df['Word'].to_list() 

CSAT_POS_df['Ortho_N_CSAT'] = CSAT_POS_df['Word'].apply(lambda x: orthographic_N(x, lexicon))
CSAT_POS_df['OLD20_CSAT'] = CSAT_POS_df['Word'].apply(lambda x: OLD20(x, lexicon))
CSAT_POS_df

            Word   Freq       POS  Ortho_N_CSAT  OLD20_CSAT
0            the  38303     minor             3        1.55
1             to  21665     minor             6        1.20
2              a  17505  minor|NN             1        1.45
3             of  17171     minor             6        1.55
4            and  16818     minor             6        1.20
...          ...    ...       ...           ...         ...
16349      vomit      1     VB|NN             0        2.45
16350  surpluses      1        NN             0        3.30
16351   resented      1     VB|JJ             0        2.15
16352     winded      1     JJ|VB             3        1.75
16353    tersely      1        RB             0        2.70

[16354 rows x 5 columns]

In [40]:
lexicon = CSAT_only_POS_df['Word'].to_list() 

CSAT_only_POS_df['Ortho_N_CSAT(only)'] = CSAT_only_POS_df['Word'].apply(lambda x: orthographic_N(x, lexicon))
CSAT_only_POS_df['OLD20_CSAT(only)'] = CSAT_only_POS_df['Word'].apply(lambda x: OLD20(x, lexicon))
CSAT_only_POS_df

            Word   Freq       POS  Ortho_N_CSAT(only)  OLD20_CSAT(only)
0            the  21540     minor                   2              1.60
1             to  12665     minor                   4              1.35
2             of  10010     minor                   5              1.60
3              a   9773  minor|NN                   1              1.45
4            and   8974     minor                   6              1.25
...          ...    ...       ...                 ...               ...
14004   fortress      1        NN                   0              2.80
14005    arabian      1     NN|JJ                   0              2.75
14006   sapphire      1        NN                   0              3.60
14007  sandstone      1        NN                   0              3.75
14008     doubly      1        RB                   1              2.55

[14009 rows x 5 columns]

In [41]:
lexicon = textbook_only_POS_df['Word'].to_list() 

textbook_only_POS_df['Ortho_N_Textbook'] = textbook_only_POS_df['Word'].apply(lambda x: orthographic_N(x, lexicon))
textbook_only_POS_df['OLD20_Textbook'] = textbook_only_POS_df['Word'].apply(lambda x: OLD20(x, lexicon))
textbook_only_POS_df

                 Word   Freq       POS  Ortho_N_Textbook  OLD20_Textbook
0                 the  16763     minor                 3            1.55
1                  to   9000     minor                 6            1.25
2                 and   7844     minor                 6            1.20
3                   a   7732  minor|NN                 1            1.45
4                  of   7161     minor                 6            1.55
...               ...    ...       ...               ...             ...
11796        deathbed      1        NN                 0            3.10
11797        elegance      1        NN                 0            3.20
11798  geographically      1        RB                 0            5.60
11799      breakfasts      1     NN|VB                 0            4.30
11800        maturity      1        NN                 0            3.35

[11801 rows x 5 columns]

In [42]:
CSAT_only_POS_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_only_POS_N.xlsx'), index=False)
textbook_only_POS_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'textbook_only_POS_N.xlsx'), index=False)
CSAT_POS_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_POS_N.xlsx'), index=False)

In [55]:
CSAT_only_POS_df.columns= ['Word', 'CSAT_only_Freq', 'POS', 'Ortho_N_CSAT(only)', 'OLD20_CSAT(only)']
textbook_only_POS_df.columns= ['Word', 'Textbook_only_Freq', 'POS', 'Ortho_N_Textbook(only)', 'OLD20_Textbook(only)']
CSAT_POS_df.columns= ['Word', 'CSAT_Freq', 'POS', 'Ortho_N_CSAT', 'OLD20_CSAT']

In [68]:
CSAT_df = pd.merge(pd.merge(CSAT_only_POS_df.drop(columns=['POS']), textbook_only_POS_df, on='Word', how='outer').drop(columns=['POS']), CSAT_POS_df, on='Word', how='outer')
CSAT_df

,Word,CSAT_only_Freq,Ortho_N_CSAT(only),OLD20_CSAT(only),Textbook_only_Freq,Ortho_N_Textbook(only),OLD20_Textbook(only),CSAT_Freq,POS,Ortho_N_CSAT,OLD20_CSAT
0,a,9773.0,1.0,1.45,7732.0,1.0,1.45,17505,minor|NN,1,1.45
1,aaron,1.0,1.0,1.95,6.0,0.0,2.00,7,NN,1,1.85
2,abandon,5.0,0.0,3.05,2.0,0.0,3.00,7,VB|NN,0,2.90
3,abandoned,5.0,0.0,3.50,7.0,0.0,3.60,12,VB|JJ,0,3.50
4,abandoning,3.0,0.0,3.60,NaN,NaN,NaN,3,VB,0,3.60
...,...,...,...,...,...,...,...,...,...,...,...
16349,zombies,NaN,NaN,NaN,3.0,0.0,2.65,3,NN,0,2.60
16350,zone,6.0,7.0,1.40,13.0,7.0,1.40,19,NN,7,1.40
16351,zones,8.0,4.0,1.60,9.0,4.0,1.60,17,NN,4,1.60
16352,zoo,21.0,1.0,1.85,10.0,4.0,1.70,31,NN,4,1.70
16353,zoologist,2.0,0.0,3.90,NaN,NaN,NaN,2,NN,0,3.90

In [69]:
CSAT_df['Length'] = CSAT_df['Word'].apply(lambda x: len(x))
relative_unit = 1000000
CSAT_df['CSAT_RFreq'] = CSAT_df['CSAT_Freq'] / relative_unit
CSAT_df['CSAT_only_RFreq'] = CSAT_df['CSAT_only_Freq'] / relative_unit
CSAT_df['Textbook_only_RFreq'] = CSAT_df['Textbook_only_Freq'] / relative_unit

In [70]:
CSAT_df.columns, len(CSAT_df.columns)

(Index(['Word', 'CSAT_only_Freq', 'Ortho_N_CSAT(only)', 'OLD20_CSAT(only)',
        'Textbook_only_Freq', 'Ortho_N_Textbook(only)', 'OLD20_Textbook(only)',
        'CSAT_Freq', 'POS', 'Ortho_N_CSAT', 'OLD20_CSAT', 'Length',
        'CSAT_RFreq', 'CSAT_only_RFreq', 'Textbook_only_RFreq'],
       dtype='object'),
 15)

In [71]:
CSAT_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16354 entries, 0 to 16353
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Word                    16354 non-null  object
 1   CSAT_only_Freq          14009 non-null  float64
 2   Ortho_N_CSAT(only)      14009 non-null  float64
 3   OLD20_CSAT(only)        14009 non-null  float64
 4   Textbook_only_Freq      11801 non-null  float64
 5   Ortho_N_Textbook(only)  11801 non-null  float64
 6   OLD20_Textbook(only)    11801 non-null  float64
 7   CSAT_Freq               16354 non-null  int64
 8   POS                     16354 non-null  object
 9   Ortho_N_CSAT            16354 non-null  int64
 10  OLD20_CSAT              16354 non-null  float64
 11  Length                  16354 non-null  int64
 12  CSAT_RFreq              16354 non-null  float64
 13  CSAT_only_RFreq         14009 non-null  float64
 14  Textbook_only_RFreq     11801 non-null  float64
dtypes: float64(10), int64(3), object(2)
memory usage: 1.9+ MB

In [72]:
CSAT_df = CSAT_df[['Word', 'Length', 
                   'CSAT_Freq', 'CSAT_only_Freq', 'Textbook_only_Freq', 'CSAT_RFreq', 'CSAT_only_RFreq', 'Textbook_only_RFreq', 
                   'Ortho_N_CSAT', 'Ortho_N_CSAT(only)', 'Ortho_N_Textbook(only)', 
                   'OLD20_CSAT', 'OLD20_CSAT(only)', 'OLD20_Textbook(only)', 
                   'POS']]
CSAT_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_final.xlsx'), index=False)
CSAT_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16354 entries, 0 to 16353
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Word                    16354 non-null  object
 1   Length                  16354 non-null  int64
 2   CSAT_Freq               16354 non-null  int64
 3   CSAT_only_Freq          14009 non-null  float64
 4   Textbook_only_Freq      11801 non-null  float64
 5   CSAT_RFreq              16354 non-null  float64
 6   CSAT_only_RFreq         14009 non-null  float64
 7   Textbook_only_RFreq     11801 non-null  float64
 8   Ortho_N_CSAT            16354 non-null  int64
 9   Ortho_N_CSAT(only)      14009 non-null  float64
 10  Ortho_N_Textbook(only)  11801 non-null  float64
 11  OLD20_CSAT              16354 non-null  float64
 12  OLD20_CSAT(only)        14009 non-null  float64
 13  OLD20_Textbook(only)    11801 non-null  float64
 14  POS                     16354 non-null  object
dtypes: float64(10), int64(3), object(2)
memory usage: 1.9+ MB

## CSAT + E-lexicon-proj

## latest update

In [142]:
E_lexicon_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'E_lexicon_preprocessed.xlsx'))
E_lexicon_df['Word'] = E_lexicon_df['Word'].astype(str)
E_lexicon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Word                           40481 non-null  object
 1   Length                         40481 non-null  int64
 2   Freq_KF                        32552 non-null  float64
 3   Freq_HAL                       40481 non-null  int64
 4   SUBTLWF                        35515 non-null  float64
 5   SUBTLCD                        35515 non-null  float64
 6   Ortho_N                        40481 non-null  int64
 7   Phono_N                        40481 non-null  int64
 8   OLD                            39382 non-null  float64
 9   PLD                            39382 non-null  float64
 10  Concreteness_Rating            23562 non-null  float64
 11  Semantic_Neighborhood_Density  39241 non-null  float64
 12  Semantic_Neighbors             39241 non-null  float64
 13  Semantic_Diversity             25858 non-null  float64
 14  Age_Of_Acquisition             31440 non-null  float64
 15  Body_Object_Interaction        8984 non-null   float64
 16  Emotional_Valence              12742 non-null  float64
 17  Emotional_Arousal              12742 non-null  float64
 18  Emotional_Dominance            12742 non-null  float64
 19  Assoc_Freq_R1                  24226 non-null  float64
 20  Assoc_Types_R1                 24226 non-null  float64
 21  Assoc_Freq_R123                29722 non-null  float64
 22  Assoc_Types_R123               29722 non-null  float64
 23  POS                            39903 non-null  object
 24  I_Mean_RT                      40468 non-null  float64
 25  I_Zscore                       40468 non-null  float64
 26  I_SD                           40450 non-null  float64
 27  Obs                            40468 non-null  float64
 28  I_Mean_Accuracy                40481 non-null  float64
 29  I_NMG_Mean_RT                  40481 non-null  float64
 30  I_NMG_Zscore                   40481 non-null  float64
 31  I_NMG_SD                       40477 non-null  float64
 32  I_NMG_Obs                      40481 non-null  int64
 33  I_NMG_Mean_Accuracy            40481 non-null  float64
dtypes: float64(27), int64(5), object(2)
memory usage: 10.5+ MB

In [143]:
CSAT_df_path = os.path.join(corpora_dir, 'merged_corpora', 'CSAT_final.xlsx')
CSAT_df = pd.read_excel(CSAT_df_path)
CSAT_df

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,CSAT_RFreq,CSAT_only_RFreq,Textbook_only_RFreq,Ortho_N_CSAT,Ortho_N_CSAT(only),Ortho_N_Textbook(only),OLD20_CSAT,OLD20_CSAT(only),OLD20_Textbook(only),POS
0,a,1,17505,9773.0,7732.0,0.017505,0.009773,0.007732,1,1.0,1.0,1.45,1.45,1.45,minor|NN
1,aaron,5,7,1.0,6.0,0.000007,0.000001,0.000006,1,1.0,0.0,1.85,1.95,2.00,NN
2,abandon,7,7,5.0,2.0,0.000007,0.000005,0.000002,0,0.0,0.0,2.90,3.05,3.00,VB|NN
3,abandoned,9,12,5.0,7.0,0.000012,0.000005,0.000007,0,0.0,0.0,3.50,3.50,3.60,VB|JJ
4,abandoning,10,3,3.0,NaN,0.000003,0.000003,NaN,0,0.0,NaN,3.60,3.60,NaN,VB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16349,zombies,7,3,NaN,3.0,0.000003,NaN,0.000003,0,NaN,0.0,2.60,NaN,2.65,NN
16350,zone,4,19,6.0,13.0,0.000019,0.000006,0.000013,7,7.0,7.0,1.40,1.40,1.40,NN
16351,zones,5,17,8.0,9.0,0.000017,0.000008,0.000009,4,4.0,4.0,1.60,1.60,1.60,NN
16352,zoo,3,31,21.0,10.0,0.000031,0.000021,0.000010,4,1.0,4.0,1.70,1.85,1.70,NN
16353,zoologist,9,2,2.0,NaN,0.000002,0.000002,NaN,0,0.0,NaN,3.90,3.90,NaN,NN

In [45]:
CSAT_df['CSAT_Freq'].sum(), CSAT_df['CSAT_only_Freq'].sum(), CSAT_df['Textbook_only_Freq'].sum()

(np.int64(709417), np.float64(409876.0), np.float64(299541.0))

In [46]:
# 값은 같네.
CSAT_df['CSAT_Freq'].sum() - (CSAT_df['CSAT_only_Freq'].sum() + CSAT_df['Textbook_only_Freq'].sum())

np.float64(0.0)

In [144]:
target_cols = ['Word', 
                'CSAT_Freq', 'CSAT_only_Freq', 'Textbook_only_Freq',
                'Ortho_N_CSAT', 'Ortho_N_CSAT(only)', 'Ortho_N_Textbook(only)',
                'OLD20_CSAT', 'OLD20_CSAT(only)', 'OLD20_Textbook(only)']
CSAT_df = CSAT_df[target_cols]
CSAT_df

,Word,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Ortho_N_CSAT,Ortho_N_CSAT(only),Ortho_N_Textbook(only),OLD20_CSAT,OLD20_CSAT(only),OLD20_Textbook(only)
0,a,17505,9773.0,7732.0,1,1.0,1.0,1.45,1.45,1.45
1,aaron,7,1.0,6.0,1,1.0,0.0,1.85,1.95,2.00
2,abandon,7,5.0,2.0,0,0.0,0.0,2.90,3.05,3.00
3,abandoned,12,5.0,7.0,0,0.0,0.0,3.50,3.50,3.60
4,abandoning,3,3.0,NaN,0,0.0,NaN,3.60,3.60,NaN
...,...,...,...,...,...,...,...,...,...,...
16349,zombies,3,NaN,3.0,0,NaN,0.0,2.60,NaN,2.65
16350,zone,19,6.0,13.0,7,7.0,7.0,1.40,1.40,1.40
16351,zones,17,8.0,9.0,4,4.0,4.0,1.60,1.60,1.60
16352,zoo,31,21.0,10.0,4,1.0,4.0,1.70,1.85,1.70
16353,zoologist,2,2.0,NaN,0,0.0,NaN,3.90,3.90,NaN

In [145]:
rename_cols = {
    'CSAT_Freq': 'Freq_KE', 
    'CSAT_only_Freq': 'Freq_KE(EXAM)', 
    'Textbook_only_Freq': 'Freq_KE(TEXTBOOK)',
    'Ortho_N_CSAT': 'Ortho_N_KE', 
    'Ortho_N_CSAT(only)': 'Ortho_N_KE(EXAM)', 
    'Ortho_N_Textbook(only)': 'Ortho_N_KE(TEXTBOOK)',
    'OLD20_CSAT': 'OLD_KE', 
    'OLD20_CSAT(only)': 'OLD_KE(EXAM)', 
    'OLD20_Textbook(only)': 'OLD_KE(TEXTBOOK)'
}
CSAT_df.rename(columns=rename_cols, inplace=True)
CSAT_df

/var/folders/3t/7cyq0j713bn7qcyfypl8dx3w0000gn/T/ipykernel_58480/86622799.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CSAT_df.rename(columns=rename_cols, inplace=True)

,Word,Freq_KE,Freq_KE(EXAM),Freq_KE(TEXTBOOK),Ortho_N_KE,Ortho_N_KE(EXAM),Ortho_N_KE(TEXTBOOK),OLD_KE,OLD_KE(EXAM),OLD_KE(TEXTBOOK)
0,a,17505,9773.0,7732.0,1,1.0,1.0,1.45,1.45,1.45
1,aaron,7,1.0,6.0,1,1.0,0.0,1.85,1.95,2.00
2,abandon,7,5.0,2.0,0,0.0,0.0,2.90,3.05,3.00
3,abandoned,12,5.0,7.0,0,0.0,0.0,3.50,3.50,3.60
4,abandoning,3,3.0,NaN,0,0.0,NaN,3.60,3.60,NaN
...,...,...,...,...,...,...,...,...,...,...
16349,zombies,3,NaN,3.0,0,NaN,0.0,2.60,NaN,2.65
16350,zone,19,6.0,13.0,7,7.0,7.0,1.40,1.40,1.40
16351,zones,17,8.0,9.0,4,4.0,4.0,1.60,1.60,1.60
16352,zoo,31,21.0,10.0,4,1.0,4.0,1.70,1.85,1.70
16353,zoologist,2,2.0,NaN,0,0.0,NaN,3.90,3.90,NaN

In [146]:
# 겹치는 col(Word) 1개 (10+34-1 = 43)
CSAT_df.columns, E_lexicon_df.columns, len(CSAT_df.columns), len(E_lexicon_df.columns)

(Index(['Word', 'Freq_KE', 'Freq_KE(EXAM)', 'Freq_KE(TEXTBOOK)', 'Ortho_N_KE',
        'Ortho_N_KE(EXAM)', 'Ortho_N_KE(TEXTBOOK)', 'OLD_KE', 'OLD_KE(EXAM)',
        'OLD_KE(TEXTBOOK)'],
       dtype='object'),
 Index(['Word', 'Length', 'Freq_KF', 'Freq_HAL', 'SUBTLWF', 'SUBTLCD',
        'Ortho_N', 'Phono_N', 'OLD', 'PLD', 'Concreteness_Rating',
        'Semantic_Neighborhood_Density', 'Semantic_Neighbors',
        'Semantic_Diversity', 'Age_Of_Acquisition', 'Body_Object_Interaction',
        'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance',
        'Assoc_Freq_R1', 'Assoc_Types_R1', 'Assoc_Freq_R123',
        'Assoc_Types_R123', 'POS', 'I_Mean_RT', 'I_Zscore', 'I_SD', 'Obs',
        'I_Mean_Accuracy', 'I_NMG_Mean_RT', 'I_NMG_Zscore', 'I_NMG_SD',
        'I_NMG_Obs', 'I_NMG_Mean_Accuracy'],
       dtype='object'),
 10,
 34)

In [147]:
rename_cols = {
    'SUBTLWF' : 'Freq_SUBTLEX',
    'I_Mean_RT' : 'LDT_RT_MEAN',
    'I_Zscore' : 'LDT_RT_ZSCORE', 
    'I_SD' : 'LDT_RT_SD', 
    'Obs' : 'LDT_RT_OBS',
    'I_Mean_Accuracy' : 'LDT_ACC_MEAN', 
    'I_NMG_Mean_RT' : 'NMG_RT_MEAN', 
    'I_NMG_Zscore' : 'NMG_RT_ZSCORE', 
    'I_NMG_SD' : 'NMG_RT_SD',
    'I_NMG_Obs' : 'NMG_RT_OBS',
    'I_NMG_Mean_Accuracy' : 'NMG_ACC_MEAN'
}
E_lexicon_df.rename(columns=rename_cols, inplace=True)
E_lexicon_df

,Word,Length,Freq_KF,Freq_HAL,Freq_SUBTLEX,SUBTLCD,Ortho_N,Phono_N,OLD,PLD,...,LDT_RT_MEAN,LDT_RT_ZSCORE,LDT_RT_SD,LDT_RT_OBS,LDT_ACC_MEAN,NMG_RT_MEAN,NMG_RT_ZSCORE,NMG_RT_SD,NMG_RT_OBS,NMG_ACC_MEAN
0,a,1,23237.0,10610626,20415.27,99.93,1,8,1.45,1.00,...,798.917,-0.013,333.849,24.0,0.73,662.087,-0.323,174.691,23,0.958
1,aah,3,1.0,222,52.71,7.56,2,0,1.85,3.00,...,816.429,0.214,186.029,21.0,0.62,646.400,-0.349,130.445,25,0.926
2,aaron,5,7.0,10806,14.65,1.93,3,2,1.85,1.60,...,736.062,-0.111,289.010,32.0,0.97,686.111,-0.203,179.290,27,1.000
3,aback,5,2.0,387,0.29,0.18,0,2,1.95,1.85,...,796.267,0.110,171.607,15.0,0.45,596.538,-0.550,89.453,26,0.963
4,abacus,6,NaN,513,0.24,0.12,0,0,2.90,2.90,...,964.400,0.655,488.996,15.0,0.47,792.688,0.309,200.186,16,0.615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zoom,4,NaN,4920,3.55,1.29,4,7,1.70,1.55,...,549.758,-0.762,97.649,33.0,1.00,639.857,-0.441,108.340,28,1.000
40477,zooming,7,1.0,523,0.63,0.31,3,3,1.85,1.85,...,709.690,-0.293,283.106,29.0,0.88,672.370,-0.218,92.353,27,1.000
40478,zooms,5,1.0,385,0.06,0.04,3,5,1.80,1.75,...,666.933,-0.476,232.109,30.0,0.94,613.833,-0.552,88.295,24,1.000
40479,zucchini,8,NaN,314,0.96,0.25,0,0,3.75,2.90,...,848.679,0.239,259.819,28.0,0.85,756.000,0.207,209.064,23,0.958
40480,zurich,6,2.0,1770,2.43,0.74,0,0,2.80,2.20,...,763.000,0.091,184.257,21.0,0.64,822.640,0.213,221.482,25,0.893

In [148]:
KE_E_final_df = pd.merge(CSAT_df, E_lexicon_df, on='Word', how='outer')
KE_E_final_df

,Word,Freq_KE,Freq_KE(EXAM),Freq_KE(TEXTBOOK),Ortho_N_KE,Ortho_N_KE(EXAM),Ortho_N_KE(TEXTBOOK),OLD_KE,OLD_KE(EXAM),OLD_KE(TEXTBOOK),...,LDT_RT_MEAN,LDT_RT_ZSCORE,LDT_RT_SD,LDT_RT_OBS,LDT_ACC_MEAN,NMG_RT_MEAN,NMG_RT_ZSCORE,NMG_RT_SD,NMG_RT_OBS,NMG_ACC_MEAN
0,a,17505.0,9773.0,7732.0,1.0,1.0,1.0,1.45,1.45,1.45,...,798.917,-0.013,333.849,24.0,0.73,662.087,-0.323,174.691,23,0.958
1,aah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,816.429,0.214,186.029,21.0,0.62,646.400,-0.349,130.445,25,0.926
2,aaron,7.0,1.0,6.0,1.0,1.0,0.0,1.85,1.95,2.00,...,736.062,-0.111,289.010,32.0,0.97,686.111,-0.203,179.290,27,1.000
3,aback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,796.267,0.110,171.607,15.0,0.45,596.538,-0.550,89.453,26,0.963
4,abacus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,964.400,0.655,488.996,15.0,0.47,792.688,0.309,200.186,16,0.615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zoom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,549.758,-0.762,97.649,33.0,1.00,639.857,-0.441,108.340,28,1.000
40477,zooming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,709.690,-0.293,283.106,29.0,0.88,672.370,-0.218,92.353,27,1.000
40478,zooms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,666.933,-0.476,232.109,30.0,0.94,613.833,-0.552,88.295,24,1.000
40479,zucchini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,848.679,0.239,259.819,28.0,0.85,756.000,0.207,209.064,23,0.958
40480,zurich,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,763.000,0.091,184.257,21.0,0.64,822.640,0.213,221.482,25,0.893

In [149]:
KE_E_final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 43 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Word                           40481 non-null  object
 1   Freq_KE                        16354 non-null  float64
 2   Freq_KE(EXAM)                  14009 non-null  float64
 3   Freq_KE(TEXTBOOK)              11801 non-null  float64
 4   Ortho_N_KE                     16354 non-null  float64
 5   Ortho_N_KE(EXAM)               14009 non-null  float64
 6   Ortho_N_KE(TEXTBOOK)           11801 non-null  float64
 7   OLD_KE                         16354 non-null  float64
 8   OLD_KE(EXAM)                   14009 non-null  float64
 9   OLD_KE(TEXTBOOK)               11801 non-null  float64
 10  Length                         40481 non-null  int64
 11  Freq_KF                        32552 non-null  float64
 12  Freq_HAL                       40481 non-null  int64
 13  Freq_SUBTLEX                   35515 non-null  float64
 14  SUBTLCD                        35515 non-null  float64
 15  Ortho_N                        40481 non-null  int64
 16  Phono_N                        40481 non-null  int64
 17  OLD                            39382 non-null  float64
 18  PLD                            39382 non-null  float64
 19  Concreteness_Rating            23562 non-null  float64
 20  Semantic_Neighborhood_Density  39241 non-null  float64
 21  Semantic_Neighbors             39241 non-null  float64
 22  Semantic_Diversity             25858 non-null  float64
 23  Age_Of_Acquisition             31440 non-null  float64
 24  Body_Object_Interaction        8984 non-null   float64
 25  Emotional_Valence              12742 non-null  float64
 26  Emotional_Arousal              12742 non-null  float64
 27  Emotional_Dominance            12742 non-null  float64
 28  Assoc_Freq_R1                  24226 non-null  float64
 29  Assoc_Types_R1                 24226 non-null  float64
 30  Assoc_Freq_R123                29722 non-null  float64
 31  Assoc_Types_R123               29722 non-null  float64
 32  POS                            39903 non-null  object
 33  LDT_RT_MEAN                    40468 non-null  float64
 34  LDT_RT_ZSCORE                  40468 non-null  float64
 35  LDT_RT_SD                      40450 non-null  float64
 36  LDT_RT_OBS                     40468 non-null  float64
 37  LDT_ACC_MEAN                   40481 non-null  float64
 38  NMG_RT_MEAN                    40481 non-null  float64
 39  NMG_RT_ZSCORE                  40481 non-null  float64
 40  NMG_RT_SD                      40477 non-null  float64
 41  NMG_RT_OBS                     40481 non-null  int64
 42  NMG_ACC_MEAN                   40481 non-null  float64
dtypes: float64(36), int64(5), object(2)
memory usage: 13.3+ MB

In [150]:
# HAL 혼자 빈도의 범위에 0이 들어 있어 0 freq -> nan 처리.
KE_E_final_df['Freq_HAL'] = KE_E_final_df['Freq_HAL'].replace(0, np.nan)

# SUBTLEX 빈도는 백만 단어 기준이라 이를 고려해서 변환.
MILLION = 1000000.0
KE_E_final_df['Freq_SUBTLEX'] = KE_E_final_df['Freq_SUBTLEX'] * 51.0

KE_E_final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 43 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Word                           40481 non-null  object
 1   Freq_KE                        16354 non-null  float64
 2   Freq_KE(EXAM)                  14009 non-null  float64
 3   Freq_KE(TEXTBOOK)              11801 non-null  float64
 4   Ortho_N_KE                     16354 non-null  float64
 5   Ortho_N_KE(EXAM)               14009 non-null  float64
 6   Ortho_N_KE(TEXTBOOK)           11801 non-null  float64
 7   OLD_KE                         16354 non-null  float64
 8   OLD_KE(EXAM)                   14009 non-null  float64
 9   OLD_KE(TEXTBOOK)               11801 non-null  float64
 10  Length                         40481 non-null  int64
 11  Freq_KF                        32552 non-null  float64
 12  Freq_HAL                       39965 non-null  float64
 13  Freq_SUBTLEX                   35515 non-null  float64
 14  SUBTLCD                        35515 non-null  float64
 15  Ortho_N                        40481 non-null  int64
 16  Phono_N                        40481 non-null  int64
 17  OLD                            39382 non-null  float64
 18  PLD                            39382 non-null  float64
 19  Concreteness_Rating            23562 non-null  float64
 20  Semantic_Neighborhood_Density  39241 non-null  float64
 21  Semantic_Neighbors             39241 non-null  float64
 22  Semantic_Diversity             25858 non-null  float64
 23  Age_Of_Acquisition             31440 non-null  float64
 24  Body_Object_Interaction        8984 non-null   float64
 25  Emotional_Valence              12742 non-null  float64
 26  Emotional_Arousal              12742 non-null  float64
 27  Emotional_Dominance            12742 non-null  float64
 28  Assoc_Freq_R1                  24226 non-null  float64
 29  Assoc_Types_R1                 24226 non-null  float64
 30  Assoc_Freq_R123                29722 non-null  float64
 31  Assoc_Types_R123               29722 non-null  float64
 32  POS                            39903 non-null  object
 33  LDT_RT_MEAN                    40468 non-null  float64
 34  LDT_RT_ZSCORE                  40468 non-null  float64
 35  LDT_RT_SD                      40450 non-null  float64
 36  LDT_RT_OBS                     40468 non-null  float64
 37  LDT_ACC_MEAN                   40481 non-null  float64
 38  NMG_RT_MEAN                    40481 non-null  float64
 39  NMG_RT_ZSCORE                  40481 non-null  float64
 40  NMG_RT_SD                      40477 non-null  float64
 41  NMG_RT_OBS                     40481 non-null  int64
 42  NMG_ACC_MEAN                   40481 non-null  float64
dtypes: float64(37), int64(4), object(2)
memory usage: 13.3+ MB

In [151]:
KE_E_final_df.reset_index(drop=True, inplace=True)
KE_E_final_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'KE_E_final(250921-1730).xlsx'), index=False)
KE_E_final_df

,Word,Freq_KE,Freq_KE(EXAM),Freq_KE(TEXTBOOK),Ortho_N_KE,Ortho_N_KE(EXAM),Ortho_N_KE(TEXTBOOK),OLD_KE,OLD_KE(EXAM),OLD_KE(TEXTBOOK),...,LDT_RT_MEAN,LDT_RT_ZSCORE,LDT_RT_SD,LDT_RT_OBS,LDT_ACC_MEAN,NMG_RT_MEAN,NMG_RT_ZSCORE,NMG_RT_SD,NMG_RT_OBS,NMG_ACC_MEAN
0,a,17505.0,9773.0,7732.0,1.0,1.0,1.0,1.45,1.45,1.45,...,798.917,-0.013,333.849,24.0,0.73,662.087,-0.323,174.691,23,0.958
1,aah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,816.429,0.214,186.029,21.0,0.62,646.400,-0.349,130.445,25,0.926
2,aaron,7.0,1.0,6.0,1.0,1.0,0.0,1.85,1.95,2.00,...,736.062,-0.111,289.010,32.0,0.97,686.111,-0.203,179.290,27,1.000
3,aback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,796.267,0.110,171.607,15.0,0.45,596.538,-0.550,89.453,26,0.963
4,abacus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,964.400,0.655,488.996,15.0,0.47,792.688,0.309,200.186,16,0.615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zoom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,549.758,-0.762,97.649,33.0,1.00,639.857,-0.441,108.340,28,1.000
40477,zooming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,709.690,-0.293,283.106,29.0,0.88,672.370,-0.218,92.353,27,1.000
40478,zooms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,666.933,-0.476,232.109,30.0,0.94,613.833,-0.552,88.295,24,1.000
40479,zucchini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,848.679,0.239,259.819,28.0,0.85,756.000,0.207,209.064,23,0.958
40480,zurich,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,763.000,0.091,184.257,21.0,0.64,822.640,0.213,221.482,25,0.893

In [152]:
KE_E_final_df.columns, len(KE_E_final_df.columns)

(Index(['Word', 'Freq_KE', 'Freq_KE(EXAM)', 'Freq_KE(TEXTBOOK)', 'Ortho_N_KE',
        'Ortho_N_KE(EXAM)', 'Ortho_N_KE(TEXTBOOK)', 'OLD_KE', 'OLD_KE(EXAM)',
        'OLD_KE(TEXTBOOK)', 'Length', 'Freq_KF', 'Freq_HAL', 'Freq_SUBTLEX',
        'SUBTLCD', 'Ortho_N', 'Phono_N', 'OLD', 'PLD', 'Concreteness_Rating',
        'Semantic_Neighborhood_Density', 'Semantic_Neighbors',
        'Semantic_Diversity', 'Age_Of_Acquisition', 'Body_Object_Interaction',
        'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance',
        'Assoc_Freq_R1', 'Assoc_Types_R1', 'Assoc_Freq_R123',
        'Assoc_Types_R123', 'POS', 'LDT_RT_MEAN', 'LDT_RT_ZSCORE', 'LDT_RT_SD',
        'LDT_RT_OBS', 'LDT_ACC_MEAN', 'NMG_RT_MEAN', 'NMG_RT_ZSCORE',
        'NMG_RT_SD', 'NMG_RT_OBS', 'NMG_ACC_MEAN'],
       dtype='object'),
 43)

In [169]:
# replacement 0 -> nan
KE_E_final_df['Freq_KE'] = KE_E_final_df['Freq_KE'].replace(0, np.nan)
KE_E_final_df['Freq_KF'] = KE_E_final_df['Freq_KF'].replace(0, np.nan)
KE_E_final_df['Freq_HAL'] = KE_E_final_df['Freq_HAL'].replace(0, np.nan)
KE_E_final_df['Freq_SUBTLEX'] = KE_E_final_df['Freq_SUBTLEX'].replace(0, np.nan)
KE_E_final_df[['Freq_KE', 'Freq_KF', 'Freq_HAL', 'Freq_SUBTLEX']].describe()

            Freq_KE       Freq_KF      Freq_HAL  Freq_SUBTLEX
count  16354.000000  32552.000000  3.996500e+04  3.551500e+04
mean      43.378806     29.731384  1.091784e+04  1.286901e+03
std      496.466347    557.639032  1.934594e+05  2.384879e+04
min        1.000000      1.000000  1.000000e+00  1.020000e+00
25%        2.000000      1.000000  1.160000e+02  1.020000e+01
50%        4.000000      3.000000  5.000000e+02  3.621000e+01
75%       15.000000      9.000000  2.331000e+03  1.458600e+02
max    38303.000000  69971.000000  2.309903e+07  2.134713e+06

In [170]:
# 현재는 모든 freq column들의 range 통제 -> 일단 corpora 간 비교 시 0 제외.
""" 현재 값들은 각각
Freq_KE: raw
Freq_KF : raw
Freq_HAL: raw
Freq_SUBTLEX: per Million 이라 일단 전부 
"""
KE_E_final_df[['Freq_KE', 'Freq_KF', 'Freq_HAL', 'Freq_SUBTLEX']].describe()

            Freq_KE       Freq_KF      Freq_HAL  Freq_SUBTLEX
count  16354.000000  32552.000000  3.996500e+04  3.551500e+04
mean      43.378806     29.731384  1.091784e+04  1.286901e+03
std      496.466347    557.639032  1.934594e+05  2.384879e+04
min        1.000000      1.000000  1.000000e+00  1.020000e+00
25%        2.000000      1.000000  1.160000e+02  1.020000e+01
50%        4.000000      3.000000  5.000000e+02  3.621000e+01
75%       15.000000      9.000000  2.331000e+03  1.458600e+02
max    38303.000000  69971.000000  2.309903e+07  2.134713e+06

HAL 코퍼스의 정확한 크기는 약 1억 3천1백만 단어에서 1억 6천만 단어 사이(SUBTLEX 논문에서도 오타가 있고, HAL을 소개하는 논문들 간에도 수치가 약간씩 다름.) 일단 130M으로 계산.

In [171]:
# RFreq는 백만 token 기준으로 변환하고, 
BILLION = 1000000000.0
MILLION = 1000000.0

# for KE Freq
KE_E_final_df['RFreq_KE'] = KE_E_final_df['Freq_KE'] * (MILLION / 741394.0)
KE_E_final_df['RFreq_KE(EXAM)'] = KE_E_final_df['Freq_KE(EXAM)'] * (MILLION / 427444.0)
KE_E_final_df['RFreq_KE(TEXTBOOK)'] = KE_E_final_df['Freq_KE(TEXTBOOK)'] * (MILLION / 313950.0)

# for existing copora
KE_E_final_df['RFreq_KF'] = KE_E_final_df['Freq_KF'] * (MILLION / 1.01*MILLION)
KE_E_final_df['RFreq_HAL(130)'] = KE_E_final_df['Freq_HAL'] * (MILLION / 130.0*MILLION)
KE_E_final_df['RFreq_HAL(160)'] = KE_E_final_df['Freq_HAL'] * (MILLION / 160.0*MILLION)
KE_E_final_df['RFreq_SUBTLEX'] = KE_E_final_df['Freq_SUBTLEX'] * (MILLION / 51.0*MILLION)

len(KE_E_final_df.columns)

57

In [172]:
KE_E_final_df[['RFreq_KE', 'RFreq_KF', 'RFreq_HAL(130)', 'RFreq_SUBTLEX']].describe()

           RFreq_KE      RFreq_KF  RFreq_HAL(130)  RFreq_SUBTLEX
count  16354.000000  3.255200e+04    3.996500e+04   3.551500e+04
mean      58.509789  2.943701e+13    8.398335e+13   2.523335e+13
std      669.639014  5.521179e+14    1.488150e+15   4.676233e+14
min        1.348810  9.900990e+11    7.692308e+09   2.000000e+10
25%        2.697621  9.900990e+11    8.923077e+11   2.000000e+11
50%        5.395242  2.970297e+12    3.846154e+12   7.100000e+11
75%       20.232157  8.910891e+12    1.793077e+13   2.860000e+12
max    51663.487970  6.927822e+16    1.776849e+17   4.185712e+16

In [173]:
# zipf는 billion으로 변형.(+1 margin 줘서.)
BILLION = 1000000000.0
MILLION = 1000000.0

KE_E_final_df['Zipf_KE'] = np.log10(KE_E_final_df['Freq_KE'] * (BILLION / 741394.0) + 1.0)
KE_E_final_df['Zipf_KE(EXAM)'] = np.log10(KE_E_final_df['Freq_KE(EXAM)']  * (BILLION / 427444.0) + 1.0)
KE_E_final_df['Zipf_KE(TEXTBOOK)'] = np.log10(KE_E_final_df['Freq_KE(TEXTBOOK)'] * (BILLION / 313950.0) + 1.0)

# for existing copora
KE_E_final_df['Zipf_KF'] = np.log10(KE_E_final_df['Freq_KF'] * (BILLION / (1.01*MILLION)) + 1.0)
KE_E_final_df['Zipf_HAL(130)'] = np.log10(KE_E_final_df['Freq_HAL'] * (BILLION / (130.0*MILLION)) + 1.0)
KE_E_final_df['Zipf_HAL(160)'] = np.log10(KE_E_final_df['Freq_HAL'] * (BILLION / (160.0*MILLION)) + 1.0)
KE_E_final_df['Zipf_SUBTLEX'] = np.log10(KE_E_final_df['Freq_SUBTLEX'] * (BILLION / (51.0*MILLION)) + 1.0)

len(KE_E_final_df.columns)

57

In [174]:
# 이걸보면, KE 가 유독 voca size가 작다는 걸 알 수 있는 거지.
KE_E_final_df[['Zipf_KE', 'Zipf_KF', 'Zipf_HAL(130)', 'Zipf_HAL(160)', 'Zipf_SUBTLEX']].describe()

            Zipf_KE       Zipf_KF  Zipf_HAL(130)  Zipf_HAL(160)  Zipf_SUBTLEX
count  16354.000000  32552.000000   39965.000000   39965.000000  35515.000000
mean       3.887183      3.603563       3.598581       3.508698      2.912832
std        0.678768      0.623517       0.999344       0.998775      0.906372
min        3.130273      2.996117       0.939135       0.860338      1.322219
25%        3.431142      2.996117       2.951001       2.860937      2.303196
50%        3.732091      3.472946       3.585140       3.494989      2.851870
75%        4.306064      3.949970       4.253623       4.163452      3.456518
max        7.713184      7.840597       8.249650       8.159474      7.621769

In [175]:
KE_E_final_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'KE_E_final(250922-1400)-zeroEx.xlsx'), index=False)

In [176]:
# replacement nan -> 0
KE_E_final_df['Freq_KE'] = KE_E_final_df['Freq_KE'].replace(np.nan, 0)
KE_E_final_df['Freq_KF'] = KE_E_final_df['Freq_KF'].replace(np.nan, 0)
KE_E_final_df['Freq_HAL'] = KE_E_final_df['Freq_HAL'].replace(np.nan, 0)
KE_E_final_df['Freq_SUBTLEX'] = KE_E_final_df['Freq_SUBTLEX'].replace(np.nan, 0)
KE_E_final_df[['Freq_KE', 'Freq_KF', 'Freq_HAL', 'Freq_SUBTLEX']].describe()

            Freq_KE       Freq_KF      Freq_HAL  Freq_SUBTLEX
count  40481.000000  40481.000000  4.048100e+04  4.048100e+04
mean      17.524691     23.907907  1.077867e+04  1.129031e+03
std      316.267203    500.191095  1.922264e+05  2.234207e+04
min        0.000000      0.000000  0.000000e+00  0.000000e+00
25%        0.000000      1.000000  1.090000e+02  5.100000e+00
50%        0.000000      2.000000  4.830000e+02  2.499000e+01
75%        3.000000      7.000000  2.275000e+03  1.142400e+02
max    38303.000000  69971.000000  2.309903e+07  2.134713e+06

according to the Brysbert(2012, Dealing with zero word frequencies: A review
of the existing rules of thumb and a suggestion
for an evidence-based choice)

laplace transform을 사용해서 zero-freq word를 dealing 하랴.
SUBLTEX-UK 에 따르면, zipf-score를 사용하는게 좋다고 하기도 했고, 
변환 시에 상대 빈도를 다 수정하면 될 듯.

In [12]:
KE_E_final_df = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'KE_E_final(250922-1400)-zeroIn.xlsx'))

In [13]:
# zero-In
# RFreq는 1M token 기준으로 변환하고, 
BILLION = 1000000000.0
MILLION = 1000000.0

SIZE = {
    'KE': 741394.0,
    'KE(EXAM)': 427444.0,
    'KE(TEXTBOOK)': 313950.0,
    'KF': 1.01*MILLION,
    'HAL(130)': 130.0*MILLION,
    'HAL(160)': 160.0*MILLION,
    'SUBTLEX': 51.0*MILLION
}

"""
UNIQUE_TOKENS = {
    'KE': 22145.0,
    'KE(EXAM)': 17438.0,
    'KE(TEXTBOOK)': 14822.0,
    'KF': 1.01*MILLION,
    'HAL(130)': 130.0*MILLION,
    'HAL(160)': 160.0*MILLION,
    'SUBTLEX': 74286.0
}
"""

UNIQUE_TOKENS = 40481.0

# for KE Freq
KE_E_final_df['RFreq_KE'] = KE_E_final_df['Freq_KE'] * (MILLION / SIZE['KE'])
KE_E_final_df['RFreq_KE(EXAM)'] = KE_E_final_df['Freq_KE(EXAM)'] * (MILLION / SIZE['KE(EXAM)'])
KE_E_final_df['RFreq_KE(TEXTBOOK)'] = KE_E_final_df['Freq_KE(TEXTBOOK)'] * (MILLION / SIZE['KE(TEXTBOOK)'])

# for existing copora
KE_E_final_df['RFreq_KF'] = KE_E_final_df['Freq_KF'] * (MILLION / SIZE['KF'])
KE_E_final_df['RFreq_HAL(130)'] = KE_E_final_df['Freq_HAL'] * (MILLION / SIZE['HAL(130)'])
KE_E_final_df['RFreq_HAL(160)'] = KE_E_final_df['Freq_HAL'] * (MILLION / SIZE['HAL(160)'])
KE_E_final_df['RFreq_SUBTLEX'] = KE_E_final_df['Freq_SUBTLEX'] * (MILLION / SIZE['SUBTLEX'])

# zipf는 billion으로 변형.(+1 margin 줘서.)
# laplace(freq+1 & corpus-size adjustment) -> relative freq -> log : zipf 
KE_E_final_df['Zipf_KE'] = np.log10((KE_E_final_df['Freq_KE'] + 1) * (BILLION / (SIZE['KE'] + UNIQUE_TOKENS)))
KE_E_final_df['Zipf_KE(EXAM)'] = np.log10((KE_E_final_df['Freq_KE(EXAM)'] + 1) * (BILLION / (SIZE['KE(EXAM)'] + UNIQUE_TOKENS)))
KE_E_final_df['Zipf_KE(TEXTBOOK)'] = np.log10((KE_E_final_df['Freq_KE(TEXTBOOK)'] + 1) * (BILLION / (SIZE['KE(TEXTBOOK)'] + UNIQUE_TOKENS)))

# for existing copora
KE_E_final_df['Zipf_KF'] = np.log10((KE_E_final_df['Freq_KF'] + 1) * (BILLION / (SIZE['KF'] + UNIQUE_TOKENS)))
KE_E_final_df['Zipf_HAL(130)'] = np.log10((KE_E_final_df['Freq_HAL'] + 1) * (BILLION / (SIZE['HAL(130)'] + UNIQUE_TOKENS)))
KE_E_final_df['Zipf_HAL(160)'] = np.log10((KE_E_final_df['Freq_HAL'] + 1) * (BILLION / (SIZE['HAL(160)'] + UNIQUE_TOKENS)))
KE_E_final_df['Zipf_SUBTLEX'] = np.log10((KE_E_final_df['Freq_SUBTLEX'] + 1) * (BILLION / (SIZE['SUBTLEX'] + UNIQUE_TOKENS)))

len(KE_E_final_df.columns)

57

In [15]:
KE_E_final_df.to_excel(os.path.join(corpora_dir, 'merged_corpora', 'KE_E_final(250922-2300)-zeroIn.xlsx'), index=False)

In [167]:
KE_E_final_df.columns

Index(['Word', 'Freq_KE', 'Freq_KE(EXAM)', 'Freq_KE(TEXTBOOK)', 'Ortho_N_KE',
       'Ortho_N_KE(EXAM)', 'Ortho_N_KE(TEXTBOOK)', 'OLD_KE', 'OLD_KE(EXAM)',
       'OLD_KE(TEXTBOOK)', 'Length', 'Freq_KF', 'Freq_HAL', 'Freq_SUBTLEX',
       'SUBTLCD', 'Ortho_N', 'Phono_N', 'OLD', 'PLD', 'Concreteness_Rating',
       'Semantic_Neighborhood_Density', 'Semantic_Neighbors',
       'Semantic_Diversity', 'Age_Of_Acquisition', 'Body_Object_Interaction',
       'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance',
       'Assoc_Freq_R1', 'Assoc_Types_R1', 'Assoc_Freq_R123',
       'Assoc_Types_R123', 'POS', 'LDT_RT_MEAN', 'LDT_RT_ZSCORE', 'LDT_RT_SD',
       'LDT_RT_OBS', 'LDT_ACC_MEAN', 'NMG_RT_MEAN', 'NMG_RT_ZSCORE',
       'NMG_RT_SD', 'NMG_RT_OBS', 'NMG_ACC_MEAN', 'RFreq_KE', 'RFreq_KE(EXAM)',
       'RFreq_KE(TEXTBOOK)', 'RFreq_KF', 'RFreq_HAL(130)', 'RFreq_HAL(160)',
       'RFreq_SUBTLEX', 'Zipf_KE', 'Zipf_KE(EXAM)', 'Zipf_KE(TEXTBOOK)',
       'Zipf_KF', 'Zipf_HAL(130)', 'Zipf_HAL(160)', 'Zipf_SUBTLEX'],
      dtype='object')

In [ ]:
# 근데 여기서 비교할 떄에는 0인 값들이 있으니 이걸 그래도 쓰기는 좀 그럼.
# 이렇게 할 때에는 0 제외에서 비교하는데 타당해 보임.
KE_E_final_df.sort_values(by='Zipf_SUBTLEX', ascending=False).reset_index(drop=True)[:KE_E_final_df.shape[0]//2][['Zipf_KE', 'Zipf_KF', 'Zipf_HAL(130)', 'Zipf_HAL(160)', 'Zipf_SUBTLEX']].corr()

                Zipf_KE   Zipf_KF  Zipf_HAL(130)  Zipf_HAL(160)  Zipf_SUBTLEX
Zipf_KE        1.000000  0.380454       0.643996       0.644163      0.561042
Zipf_KF        0.380454  1.000000       0.385827       0.385924      0.300759
Zipf_HAL(130)  0.643996  0.385827       1.000000       0.999999      0.747699
Zipf_HAL(160)  0.644163  0.385924       0.999999       1.000000      0.747899
Zipf_SUBTLEX   0.561042  0.300759       0.747699       0.747899      1.000000

In [103]:
KE_E_final_df.sort_values(by='Zipf_SUBTLEX', ascending=False).reset_index(drop=True)[KE_E_final_df.shape[0]//2:][['Zipf_KE', 'Zipf_KF', 'Zipf_HAL(130)', 'Zipf_HAL(160)', 'Zipf_SUBTLEX']].corr()

                Zipf_KE   Zipf_KF  Zipf_HAL(130)  Zipf_HAL(160)  Zipf_SUBTLEX
Zipf_KE        1.000000  0.152223       0.176233       0.176795      0.146417
Zipf_KF        0.152223  1.000000       0.141161       0.141501     -0.012955
Zipf_HAL(130)  0.176233  0.141161       1.000000       0.999998      0.321646
Zipf_HAL(160)  0.176795  0.141501       0.999998       1.000000      0.322015
Zipf_SUBTLEX   0.146417 -0.012955       0.321646       0.322015      1.000000

# KE에는 있고, E-lexicon에는 없는 단어들..?

In [9]:
SUBTLEX = pd.read_excel(os.path.join(corpora_dir, 'E-lexicon-proj', 'SUBTLEXusExcel2007.xlsx'))
SUBTLEX['Word'] = SUBTLEX['Word'].astype(str)
SUBTLEX['Word'] = SUBTLEX['Word'].str.lower()
SUBTLEX

,Word,FREQcount,CDcount,FREQlow,Cdlow,SUBTLWF,Lg10WF,SUBTLCD,Lg10CD
0,the,1501908,8388,1339811,8388,29449.176471,6.176644,100.000000,3.923710
1,to,1156570,8383,1138435,8380,22677.843137,6.063172,99.940391,3.923451
2,a,1041179,8382,976941,8380,20415.274510,6.017526,99.928469,3.923399
3,you,2134713,8381,1595028,8376,41857.117647,6.329340,99.916547,3.923348
4,and,682780,8379,515365,8374,13387.843137,5.834281,99.892704,3.923244
...,...,...,...,...,...,...,...,...,...
74281,zoroastrian,1,1,0,0,0.019608,0.301030,0.011922,0.301030
74282,zoroastrianism,1,1,0,0,0.019608,0.301030,0.011922,0.301030
74283,zugzwang,1,1,1,1,0.019608,0.301030,0.011922,0.301030
74284,zygotes,1,1,1,1,0.019608,0.301030,0.011922,0.301030
74285,zymurgy,1,1,1,1,0.019608,0.301030,0.011922,0.301030

In [5]:
KE_minus_E = pd.read_excel(os.path.join(corpora_dir, 'merged_corpora', 'CSAT_minus_E_lexicon.xlsx'))
KE_minus_E

          Word  CSAT_only_Freq  textbook_only_Freq  CSAT_Freq
0            '            31.0                 8.0         39
1           ''             1.0                 NaN          1
2     'bambuco             1.0                 NaN          1
3        'best             1.0                 NaN          1
4      'cumbia             1.0                 NaN          1
...        ...             ...                 ...        ...
5788       zop             NaN                 5.0          5
5789     zquez             NaN                 2.0          2
5790  zukerman             3.0                 NaN          3
5791      zulu             NaN                 3.0          3
5792     zulus             1.0                 NaN          1

[5793 rows x 4 columns]

In [ ]:
# 한 3000개 정도는 그냥 E-lexicon에서 빠진 즉, SUBLTEX에는 있긴 한데, 실제로 겹치지 않는 단어는 SUBTLEX-KE 간 3천개 정도 됨.
# 오타, ;한국에서만 사용하는 단어들(super-, superintelligent) 같은 게 있는 듯.
KE_minus_E[~KE_minus_E['Word'].isin(SUBTLEX['Word'])].reset_index(drop=True)
KE_minus_E[~KE_minus_E['Word'].isin(SUBTLEX['Word'])].reset_index(drop=True).to_excel(os.path.join(corpora_dir, 'merged_corpora', 'KE_minus_SUBTLEX(full).xlsx'), index=False)